### ISSUE TITLE
Situations where StyLua should/shouldn't wrap onto new lines

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#10]
Below is an example where I'm not entirely sure if it should be wrapped or not:
```lua
error(
    "Owner `" .. tostring(owner) .. "` already has a pawn. Try deleting their currently owned pawn."
)
```
This needs to be thought about and then determined on what to do

**Comment by osyrisrblx** [comment]
You might find this video useful!

https://www.youtube.com/watch?v=0Q4kUNx85_4

**Comment by JohnnyMorganz** [comment]
Wow, that looks pretty interesting, thanks for bringing it up! I'll take a look later

**Comment by JohnnyMorganz** [comment]
I have currently made the decision that StyLua won't wrap function calls with a single argument onto new lines - but the formatting is subject to change in some cases. I feel as though it will be easier to change the formatting of specific cases in the future (or maybe even revert to what happens currently if it is deemed better).

I'm open to places where people think a single function argument *should* be pushed onto new lines, therefore I'll be leaving this issue open to act as a tracking issue for this. If you have a specific situation where you think StyLua would produce more readable code by wrapping onto new lines, do comment.

**Comment by Mullets-Gavin** [comment]
A specific situation I have with this happen to be related to specifically `assert`, where I use guards to prohibit certain types/arguments from passing through functions. An example of this code may be:

```lua
local function foo(bar)
	assert(typeof(bar) == "table", "'foo' can only be used with a table and got '" .. typeof(bar) .. "'")
end

foo('string')
```

which then formatted becomes:
```lua
local function foo(bar)
	assert(
		typeof(bar) == "table",
		"'foo' can only be used with a table and got '" .. typeof(bar) .. "'"
	)
end

foo("string")
```

This then not only adds more lines but makes my guards a bit more annoying to read if I set multiple long-line asserts one after the other. I think within this case, taking into consideration both the last argument is a string & the columns it takes up, should be a decider whether it should wrap. I am of the belief that these types of functions should *not* wrap.

I know this isn't one individual line, but for specific purposes like these, I think it should be treated as one, and which keeps original formatting & does not push into new lines.

**Comment by LastTalon** [comment]
I think they definitely should wrap. I see no reason to make the line extend that far to the right.

**Comment by KyleMit** [comment]
Thanks for your work and this discussion!

One edge case that doesn't seem covered by the updates in #29 (**Implement multiline expressions wrapping**) is when a long line is directly `return`ed.

### These Test Cases Work as Expected (don't change format) ✔

```lua
local output = node.kind == Kind.VARIABLE
	or node.kind == Kind.INT
	or node.kind == Kind.FLOAT
	or node.kind == Kind.STRING
	or node.kind == Kind.BOOLEAN
	or node.kind == Kind.NULL
	or node.kind == Kind.ENUM
	or node.kind == Kind.LIST
	or node.kind == Kind.OBJECT
return output
```

```lua
if
	node.kind == Kind.VARIABLE
	or node.kind == Kind.INT
	or node.kind == Kind.FLOAT
	or node.kind == Kind.STRING
	or node.kind == Kind.BOOLEAN
	or node.kind == Kind.NULL
	or node.kind == Kind.ENUM
	or node.kind == Kind.LIST
	or node.kind == Kind.OBJECT
then
	return "output"
end
```

### This Test Case Fails (wraps onto single line) ❌

**Input**

```lua
return node.kind == Kind.VARIABLE
  or node.kind == Kind.INT
  or node.kind == Kind.FLOAT
  or node.kind == Kind.STRING
  or node.kind == Kind.BOOLEAN
  or node.kind == Kind.NULL
  or node.kind == Kind.ENUM
  or node.kind == Kind.LIST
  or node.kind == Kind.OBJECT
```

**Output**

```lua
return node.kind == Kind.VARIABLE or node.kind == Kind.INT or node.kind == Kind.FLOAT or node.kind == Kind.STRING or node.kind == Kind.BOOLEAN or node.kind == Kind.NULL or node.kind == Kind.ENUM or node.kind == Kind.LIST or node.kind == Kind.OBJECT
```

**Comment by JohnnyMorganz** [comment]
Hey all, I've decided against keeping this as a catch-all issue as I think it is easier for me to manage if problems are separated (even though they may be linked), and I think this issue makes it a bit confusing about where to post. I'll be closing this one, but if what you have posted is still a problem, feel free to open a new issue about it and discussion can happen there.

Thanks!
