### ISSUE TITLE
Wrap long function signatures (w/ types?)

### ISSUE THREAD

**Issue by ok-nick** [JohnnyMorganz/StyLua#104]
StyLua currently formats all function signatures like this:
```lua
local function foo(bar: Instance, baz: Instance, qux: Instance, quux: Instance, corge: Instance, grault: Instance, garply: Instance, waldo: Instance, fred: Instance, plugh: Instance, xyzzy: Instance, thud: Instance)
end
```

Whereas it would be more readable to have it format like this:
```lua
local function foo(
	bar: Instance,
	baz: Instance,
	qux: Instance,
	quux: Instance,
	corge: Instance,
	grault: Instance,
	garply: Instance,
	waldo: Instance,
	fred: Instance,
	plugh: Instance,
	xyzzy: Instance,
	thud: Instance
)
end
```

Multi-lined signatures greatly improve readability, especially with complex types.
This feature is similar to eslint's [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline) or rustfmt's [fn_args_layout](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#fn_args_layout).

**Comment by JohnnyMorganz** [comment]
The reason I was hesitant about this was that I was unsure about how "nice" it really looked. JavaScript (eslint) and Rust (rustfmt) use braces to denote scope, which is why it looks somewhat better.

For something like
```lua
local function reallyLongFunctionName(thisIsAReallyLongParameter1: Instance, thisIsAReallyLongParameter2: Instance, parameter3: number)
	local x = 1
end
```
which would be formatted as
```lua
local function reallyLongFunctionName(
	thisIsAReallyLongParameter1: Instance,
	thisIsAReallyLongParameter2: Instance,
	parameter3: number
)
	local x = 1
end
```
I personally felt it looked a bit weird, especially when there are more statements within the function body. (The scope/indent just looked a bit odd in my eyes).

These are all pretty minor nitpicks though, and if the general consensus is to do so, I'm happy to follow it. My function signatures are normally quite small, so I haven't had the need for something like this - but with the example you gave, it does seem it may be a better alternative.

Happy to have a discussion about it.

**Comment by ok-nick** [comment]
I agree that it does look weird without something like Rust's brackets to declare the scope. Although in my situation with typed luau, complex types make function signatures virtually impossible to read. Without types, I'd say it's more trivial, parameters are already pretty clear.

This feature could be dependent on the character length of each type?  Or maybe add them all up and base it on that? Or to be more consistent, the length of the signature + whether or not it uses types determines wrapping?
It's hard to say what should be done to keep consistency and readability balanced.

e.g.
```lua
local function func(arg1: SomeType<MyInstance<BasePart>, GuiObject> & {key1: Instance<BasePart> & TableType, key2: BasePart, key3: MyType<Instance>}, arg2: MyType<Instance> & TableType & SomeType<Instance, GuiObject>): MyType<MyType<GuiObject>> & SomeType<Instance, BasePart>
end
```
versus
```lua
local function func(
	arg1: SomeType<
		MyInstance<BasePart>,
		GuiObject
	> & {
		key1: Instance<BasePart>
			& TableType,
		key2: BasePart,
		key3: MyType<Instance>
	},
	arg2: MyType<Instance>
		& TableType
		& SomeType<
			Instance,
			GuiObject
		>
): MyType<
	MyType<GuiObject>
> & SomeType<
	Instance,
	BasePart
>
end
```
This definitely is an extreme example with plenty of formatting mistakes, but you get the point.

**Comment by matthargett** [comment]
I agree with @ok-nick -- when you have even trivial types in the argument list, and then on the return type, the current formatting approach breaks down very quickly. I'd like to see similar functionality to what prettier has across the various typed languages that it supports, which is more in line with the original request.

**Comment by JohnnyMorganz** [comment]
> This feature could be dependent on the character length of each type? Or maybe add them all up and base it on that? Or to be more consistent, the length of the signature + whether or not it uses types determines wrapping?
> It's hard to say what should be done to keep consistency and readability balanced.

If I were to implement this, it would probably make the best sense to implement it everywhere. Using some calculation which is based on only if types are present, and the length of the type, is not intuitive for the most part.

I'll take a look at this, and see what I come up with
