### ISSUE TITLE
Panic while mutating table surrounded in parentheses

### ISSUE THREAD

**Issue by ok-nick** [JohnnyMorganz/StyLua#118]
Code:
```
({}).foo = true
```
Panic:
`
thread 'main' panicked at 'internal error: entered unreachable code: got non-parentheses expression as prefix Value { value: TableConstructor(TableConstructor { braces: ContainedSpan { tokens: (TokenReference { leading_trivia: [Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Whitespace { characters: "" } }, Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Whitespace { characters: "" } }], token: Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Symbol { symbol: LeftBrace } }, trailing_trivia: [Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Whitespace { characters: "" } }] }, TokenReference { leading_trivia: [Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Whitespace { characters: "" } }], token: Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Symbol { symbol: RightBrace } }, trailing_trivia: [Token { start_position: Position { bytes: 0, line: 0, character: 0 }, end_position: Position { bytes: 0, line: 0, character: 0 }, token_type: Whitespace { characters: "" } }] }) }, fields: Punctuated { pairs: [] } }), type_assertion: None }', stylua-0.7.0/src/formatters/block_formatter.rs:236:21
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
`

**Comment by JohnnyMorganz** [comment]
Was this triggered in conjunction with #119? Because this panic should never be triggered. It seems as though, because of #119, firstly the parentheses are being removed, so the stmt is `{}.foo = true`, which in turn indicates a non-parentheses expression as prefix.

**Comment by ok-nick** [comment]
This panic is triggered by itself without any other code
