### ISSUE TITLE
[Feature Request] Option for trailing commas

### ISSUE THREAD

**Issue by Stanzilla** [JohnnyMorganz/StyLua#125]
I would love an option to enable/disable the removal/addition of trailing commas on the last member of a table. I personally like them but not every project does.

**Comment by JohnnyMorganz** [comment]
I'm not sure about adding a configuration option for this. I understand where you are coming from, with regards to some projects not always liking the trailing comma, but this is the reason why the formatter is opinionated - it is in an attempt to enforce a consistent code style. Adding a configuration option here just opens more doors to bike shedding amongst teams.

**Comment by JohnnyMorganz** [comment]
I am closing this issue, as it is unlikely that this will be implemented. We will currently stick with always having a trailing comma, rather than having an option for it.

**Comment by otakutyrant** [comment]
It is a pity that Lua functions do not allow trailing commas.
