### ISSUE TITLE
[Suggestion] Add support for ROBLOX Lua style guide

### ISSUE THREAD

**Issue by cassis163** [JohnnyMorganz/StyLua#129]
I found this official code style guide for ROBLOX: https://roblox.github.io/lua-style-guide/. My idea is very similar to the functionality of the ```selene generate-roblox-std``` command.  I think that it would be nice to be able to generate or copy a stylua.toml that includes the official code standard rules.

**Comment by JohnnyMorganz** [comment]
The project is based off the style guide you mentioned - all the defaults should be in line with what the style guide expects. What would you expect to see in a generated `stylua.toml`, which isn't currently the default?

**Comment by cassis163** [comment]
Then I probably made a mistake in my installation process, cause I set it up today.

**Comment by JohnnyMorganz** [comment]
There are some things that we don't do ourselves, or stuff we don't do great yet. If there was something that didn't look like it follows the style guide though, I would be happy to take a look

**Comment by cassis163** [comment]
I am not sure if I missed something but is there a way to get real time formatting (like linters have)? I would like to see the output of `stylua ./src` in real time in my text editor.

**Comment by JohnnyMorganz** [comment]
Closing this issue as there is nothing actionable. If you spot a bug or something which doesn't look right, and you are following the Roblox Lua Style Guide, feel free to open a new issue
