### ISSUE TITLE
Allow use of an ignore file

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#13]
It would be really useful to have a file similar to a `.prettierignore` (something like `.styluaignore` possibly) that allows coordination of which files to format without having to pass options to command line every time. This would allow much easier adoption in git projects that are already familiar with this style of collaboration coordination.

**Comment by Dekkonot** [comment]
I feel like putting this into `stylua.toml` would be a good idea, since that's already being used as a configuration file.

**Comment by LastTalon** [comment]
It may be better to keep it separate. Lots of tools that use such files keep them separate (such as the separate `.prettierrc` and `.prettierignore` files).

There's no reason we couldn't, but it will probably be easier to use separately and will be easier to adopt if the ignore file is the same in format to other ignore files.

**Comment by JohnnyMorganz** [comment]
Should be completed as of https://github.com/JohnnyMorganz/StyLua/commit/83e3b782b30eb8335b2bc40e13f7177e70a268e7
StyLua will now search for a `.styluaignore` file, and if it is found, any patterns matched inside of it will be ignored. The format is similar to a `.gitignore` file.

With this, I also added support for providing multiple glob patterns. The `--pattern` argument has been renamed as `--glob` (with shortform `-g`). For example, running the following command:
```
stylua -g **/*.lua -g !**/*.spec.lua .
```
will format all the Lua files, apart from any files ending with `.spec.lua`, which will be ignored.
