### ISSUE TITLE
Hangable Prefix expression goes over width when it could be split

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#139]
Function call which contains long concatenated string arguments are turned into single line. Can this be fixed?

For example
```
error("11111111111111111111111111111111111111111111111"
 .. "11111111111111111111111111111111111111111111111111111111")
```

I want this to be 2 lines to be fit in 120 columns, rather than a single line of
```
error("11111111111111111111111111111111111111111111111" .. "11111111111111111111111111111111111111111111111111111111")
```

__Originally posted by @SafeteeWoW in https://github.com/JohnnyMorganz/StyLua/issues/78#issuecomment-830681358__

**Comment by JohnnyMorganz** [comment]
@SafeteeWow I just tested this, and it seems to be working as intended?
Over 120 characters, it gets formatted as:
```lua
error(
	"1111111111111111111111111111111111111111111111111111"
		.. "1111111111111111111111111111111111111111111111111111111111"
)
```

**Comment by SafeteeWoW** [comment]
Please format this file as an example
https://raw.githubusercontent.com/SafeteeWoW/LibDeflate/4fd8e298c7315d47ee3cd2a9bc71e49f77f2afb0/tests/Test.lua

**Comment by JohnnyMorganz** [comment]
Is there anything in particular to the file you wish to highlight - I couldn't see any code representing your original code sample.

I *did* see though, long lines of `("foooo" .. "barrrr" .. "bazzzzz"):format()`, where the prefix expression at the front `("foooo" .. "barrrr" .. "bazzzzz")`, is placed on a single line, but it could be hung. This could definitely be improved, but its not exactly the snippet you provided, as thats about function call arguments - is this the code you meant?

**Comment by SafeteeWoW** [comment]
The main problem is that many code is formatted beyond 120 column width,
mainly `("foooo" .. "barrrr" .. "bazzzzz"):format()`
