### ISSUE TITLE
thread 'main' has overflowed its stack when built from source

### ISSUE THREAD

**Issue by SafeteeWoW** [JohnnyMorganz/StyLua#141]
Stylua raises error message of
thread 'main' has overflowed its stack
when formatting file https://raw.githubusercontent.com/SafeteeWoW/LibDeflate/4fd8e298c7315d47ee3cd2a9bc71e49f77f2afb0/tests/Test.lua

The commit id is e545cf0bc034831d34709bce8da8638ad33f6d4f, same to the commit of 0a7b6fd2cfd4b37d07baa6e9c9b5b0061991cf0d, the commit of v0.8.1

My OS is Windows10, and I use Powershell as the terminal.
I build StyLua by git clone the repository and then `cargo build`.
Then I run `.\stylua.exe` inside target/debug folder.

Output of `cargo --version`
cargo 1.51.0 (43b129a20 2021-03-16)

However, there is no problem if I run `stylua` which comes from `cargo install stylua --version 0.8.1`

I am new to rust. Not sure why my local build behaviors differently with the package

**Comment by SafeteeWoW** [comment]
Seems the problem only occurs on Windows.
No problem when built on Ubuntu 20.04 LTS with cargo version 1.46.0 in Windows Subsystem for Linux.
Still have problem after downgrading Windows toolchain from 1.51.0 to 1.46.0

**Comment by JohnnyMorganz** [comment]
This is actually an issue with an upstream crate: https://github.com/Kampfkarren/full-moon/issues/140
By default, building from source will build a debug version. If you are building from source, make sure to include the `--release` flag, which produces a more optimised binary, and the issue should not occur.
