### ISSUE TITLE
Ignores file without `.lua` extension explicitly provided to CLI

### ISSUE THREAD

**Issue by dhruvmanila** [JohnnyMorganz/StyLua#170]
It seems that Stylua does not format a file without `.lua` extension. Is this the intended behavior?

Steps to reproduce:
```console
~/cs
❯ touch test

~/cs
❯ vi test

~/cs
❯ stylua --check test

~/cs
❯ stylua test

~/cs
❯ cat test
local function test()
  if true then return end
  local this_should_be_a_very_long_name = {"a table", "with a", "lot of values", "to make it", "format", "in separate lines"}
end

~/cs
❯ mv test test.lua

~/cs
❯ stylua test.lua

~/cs
❯ cat test.lua
local function test()
        if true then
                return
        end
        local this_should_be_a_very_long_name = {
                "a table",
                "with a",
                "lot of values",
                "to make it",
                "format",
                "in separate lines",
        }
end
```

**Comment by JohnnyMorganz** [comment]
By default, the glob set is `*.lua` (https://github.com/JohnnyMorganz/StyLua#glob-filtering), so to format items without a `.lua` ending, run `stylua --glob * --check test`.
This is done as directories are passed on the command line, so that we only look for `.lua` endings. However, maybe it makes sense, if a file is explicitly provided, to bypass the glob filter

**Comment by dhruvmanila** [comment]
Oh, right. I got it.

> This is done as directories are passed on the command line, so that we only look for .lua endings. However, maybe it makes sense, if a file is explicitly provided, to bypass the glob filter

Maybe we can check whether the provided argument is a file or directory and execute accordingly? If it is a file then we will run the formatter on it, else we will use the glob pattern to format files in the directory. 

If not, then this behavior should be mentioned in the README as it could be confusing at first.
