### ISSUE TITLE
Bug when processing unary minus

### ISSUE THREAD

**Issue by oltrep** [JohnnyMorganz/StyLua#171]
Hi!😄 

When converting
```lua
return -(-foo)
```
Or even without parentheses
```lua
return - -foo
```

Stylua does not insert a space between each `-` so it creates a comment
```lua
return --foo
```

**Comment by JohnnyMorganz** [comment]
Hm, I wonder whether this should be a location where we explicitly keep parentheses.
I think `-(-foo)` looks much better than `- -foo`
