### ISSUE TITLE
Bug when processing long comments

### ISSUE THREAD

**Issue by oltrep** [JohnnyMorganz/StyLua#172]
Hi again!

When I format something with a long comment at the end of the line
```lua
local variable = 90 --[[ ... ]]
```
Stylua currently removes the space before the comment
```lua
local variable = 90--[[ ... ]]
```

If it's a normal comment (with just `-- ...`) then it's fine, it only happens with `--[[ ]]` 🙂

**Comment by JohnnyMorganz** [comment]
Thanks for the report, but it seems this is actually a duplicate of #136 🙂 
This is fixed on the master branch, but it may be a few weeks or so until thats released (currently busy with some other work before I can finish up the stylua release). Assuming you have Rust/cargo installed, you could build from source if you wish - or use `cargo install stylua --git https://github.com/JohnnyMorganz/StyLua`
