### ISSUE TITLE
Provide filepath when formatting from stdin

### ISSUE THREAD

**Issue by disrupted** [JohnnyMorganz/StyLua#192]
Great work on the 0.9 release!

I'd like to start using the new `--search-parent-directories` option. How can I pass the filepath to stylua when formatting from stdin so that it knows where on my filesystem it should look for the config file?

**Comment by JohnnyMorganz** [comment]
StyLua uses the current working directory to determine where to search from, so you should set it to the directory containing the file you are taking in from stdin. If this isn't possible with the tools you are using, I could probably add in a `--path` argument or something similar

**Comment by disrupted** [comment]
Thanks for your quick reply. I would prefer the `--path` option you mentioned to pass in the absolute filepath.

**Comment by JohnnyMorganz** [comment]
Added this in https://github.com/JohnnyMorganz/StyLua/commit/a0d6fe00584dc9d437fecbdabd3d01a2128cf048. The option is named `--stdin-filepath`: the file it points to doesn't necessarily need to exist, just its parent directory does.

**Comment by disrupted** [comment]
@JohnnyMorganz great, thank you!
