### ISSUE TITLE
Comments in empty functions are moved next to function parentheses

### ISSUE THREAD

**Issue by ok-nick** [JohnnyMorganz/StyLua#195]
Before format:
```lua
local function foo()
	-- bar
end
```
After format once:
```lua
local function foo() 	-- bar
end
```
After format twice:
```lua
local function foo() -- bar end
```

**Comment by JohnnyMorganz** [comment]
Since this is a syntax breaking bug, for the time being I would recommend adding `-- stylua: ignore` above the function definition to unblock you
