### ISSUE TITLE
Ignore more than single line

### ISSUE THREAD

**Issue by gegoune** [JohnnyMorganz/StyLua#198]
Hey, is it possible to ignore more than single line/statement at time? I want to ignore entire block. If that's not currently supported would you consider something like

```lua
-- stylua: ignore start
multiple
blocks
-- stylua: ignore stop
```
?

Thanks! (0.9.1 works like a charm!)

**Comment by JohnnyMorganz** [comment]
This isn't currently possible (well, you could use formatting ranges on the CLI but that's the inverse of what you want, and isn't really easy to use quickly). I can take a look

**Comment by JohnnyMorganz** [comment]
#225 should add this, except using `-- stylua: ignore end` rather than `-- stylua: ignore stop`. Feel free to test it out if you want, would be great to see if it works well for you!

**Comment by gegoune** [comment]
Absolutely no need to apologise, thank you so much for doing this! Will get dev version installed and test it in few moments.

**Comment by gegoune** [comment]
It does work as expected for my simple use case, thanks a lot! 🥇

**Comment by JohnnyMorganz** [comment]
Awesome! I think the tests cover everything I can think of in a nutshell, so I'll merge it in!
I think I'll be cutting a new release in the next day or so
