### ISSUE TITLE
Format errors with `goto` as a function

### ISSUE THREAD

**Issue by mgutz** [JohnnyMorganz/StyLua#229]
Stylua version: v0.10.0
Linux binary download 

This doesn't format. Doesn't like the `goto`. 

```lua
local f = function()
-- cannot use goto as function identifier
self.goto(bufnr)
end
```

```sh
error: could not walk: lab/neostack-modules/lua/neostack-modules/mru_buffers/mru2_man.lua: IO error for operation on lab/neostack-modules/lua/neostack-modules/mru_buffers/mru2_man.lua: No such file or directory (os error 2)
```

**Comment by JohnnyMorganz** [comment]
This seems to be an issue in our parsing library (full-moon) where `goto` has been restricted as a symbol for Lua 5.2, but this has leaked into non-Lua5.2 code.

Just to confirm: this is part of a Lua 5.1 codebase right? I'm pretty sure `goto` used as a variable/function name isn't allowed in 5.2+, but I might be wrong.

**Comment by mgutz** [comment]
Yes, it's 5.1 embedded in neovim.

**Comment by bugabinga** [comment]
This is most likely because neovim uses LuaJIT, which defines some [extensions](https://luajit.org/extensions.html) to Lua 5.1.
`goto` was introduced in Lua 5.2.
