### ISSUE TITLE
Formatting from stdin in Windows Powershell always fails

### ISSUE THREAD

**Issue by bugabinga** [JohnnyMorganz/StyLua#231]
Any lua file that I feed to stylua in powershell via stdin fails like so:
```
PS C:\Users\okr> stylua --version
stylua 0.10.0
PS C:\Users\okr> bat .\test.lua
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\test.lua
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ print'yo yoyo yo'
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
PS C:\Users\okr> Get-Content .\test.lua | stylua -
Failed to format from stdin: error parsing: error occurred while tokenizing: unexpected character ﻿ at line 1, column 1
```

In `cmd.exe` it seems to work:
```
C:\Users\okr>type test.lua | stylua -
print("yo yoyo yo")
```

Also, passing the file path to stylua always works.
I have not tested Powershell Core.

- Windows 10
```
PS C:\Users\okr> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by JohnnyMorganz** [comment]
Hm strange, its failing at the first character.
Does your file contain a BOM? The parsing library used has an open issue regarding it, and it looks similar https://github.com/Kampfkarren/full-moon/issues/117

**Comment by JohnnyMorganz** [comment]
I've tried this again and I can't reproduce this locally.
What I would recommend looking into would be using the `-Encoding` parameter for `Get-Content`: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-5.1#parameters
Maybe my `Default` is different to yours?
It also looks like in latest PowerShell (7.1), the `-Encoding` parameters have changed and you can use `utf8NoBom` (which is the new default): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.1#parameters - maybe updating PowerShell might help?

**Comment by bugabinga** [comment]
The files do not seem to contain a BOM:
```
PS D:\Workspaces\misc\dotfiles\neovim> hexyl -n 3 .\init.lua
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 2d 2d 20                ┊                         │--      ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```
The expected value for a BOM is `0xEF,0xBB,0xBF` according to [Wikipedia](https://en.wikipedia.org/wiki/Byte_order_mark).

Adding `-Encoding UTF8` to `Get-Content` does not make a difference in my tests. Neither do any other encodings available in Powershell 5.
`Get-Content` is also unlikely to be the problem since `bat` also fails:
```
PS D:\Workspaces\misc\dotfiles\neovim> bat .\init.lua | stylua -
Failed to format from stdin: error parsing: error occurred while tokenizing: unexpected character ﻿ at line 1, column 1
```

However, I can confirm that it works in Powershell 7.1!
Updating Powershell 5 however is tricky, since it is part of the Windows 10 base.
For example, Powershell 5 is `powershell.exe` while Powershell 7 is `pwsh.exe`, so people usually shell out to `powershell.exe` because it is guaranteed to be available.

It seems the whole situation regarding Powershell, BOMs and UTF8 is a [large mess](https://stackoverflow.com/questions/65191663/write-output-with-no-bom/65192064#65192064).

But, assuming Powershell 5 adds a BOM automatically while piping the data to stylua, do we expect stylua to fail?

**Comment by JohnnyMorganz** [comment]
> But, assuming Powershell 5 adds a BOM automatically while piping the data to stylua, do we expect stylua to fail?

In the ideal case, StyLua should definitely be handling a BOM cleanly. As mentioned earlier, there is an issue open in the upstream parsing crate to solve it - https://github.com/Kampfkarren/full-moon/issues/117.
Just wanted to point out the PowerShell Get-Content BOM stuff to provide a workaround for now, surprising it's also an issue for bat which is strange.
