### ISSUE TITLE
Strange behavior with range formatting

### ISSUE THREAD

**Issue by jose-elias-alvarez** [JohnnyMorganz/StyLua#239]
StyLua version: 0.10.1 (installed via `cargo install stylua`)

Given the following content, which contains an extra space around each side of each equals sign:

```lua
local should_format  =  "should format"
local will_fail  =  {
	will_fail  =  "will fail",
	will_also_fail  =  "will also fail",
}
local should_also_format  =  "should also format"
```

When specifying a range delimiting one line at a time, it seems that range formatting succeeds for the first and last line, but fails for the second, third, and fourth lines. 

I've tested this out with the StyLua VS Code plugin, [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) (a Neovim plugin with support for range formatting), and directly from the command line (using `cat` and the byte indexes provided by Neovim), and the results seem consistent. Strangely, selecting the entire `will_fail` table successfully formats that range.

This block produces similar results. Individual lines will not format when selected, but the entire block will:

```lua
local my_function  =  function()
	local will_fail  =  "will fail"
end
```

Formatting the entire document at a time via the same methods work as expected, as does range formatting over the entire document. It also seems to be config-independent, since I've tested it in a few repositories with different config files as well as without a config.

Let me know if I can provide any more information (or if this is a misunderstand of how range formatting works in StyLua).

**Comment by JohnnyMorganz** [comment]
Yeah, this is a limitation in the current implementation of range formatting.

Currently, a **whole statement** must be encompassed within the range for it to be formatted. (Statement being the `stat` item in EBNF at https://www.lua.org/manual/5.1/manual.html#8)
As you rightly point out, selecting a whole LocalAssignment statement node will format using range formatting, but selected a field inside a table won't format - you need to select the whole assignment statement node.
If a statement node is partially in the range, it will not format

Strange that in your second example, selecting the LocalAssignment node within the function block doesn't get formatted - that is not expected.

This could probably be changed sometime in the future where you can select virtually anything, but it leads to some weird behaviour which I need to work out. Issues happen where only a partial format is done, and it leads to malformed formatting as some formatting its reliant on the syntax around the code which, if not included, can cause some strange stuff

**Comment by jose-elias-alvarez** [comment]
Thank you for the clarification! I've played around with it a bit more and it does seem that statements within other statements will not get formated, as in this example:

```lua
local my_function  =  function()
	local function other_function()
		local will_also_fail  =  "will fail"
	end
end
```

If I understand your explanation and the definitions correctly, formatting over the range that contains `other_function` (lines 2-4) should format the line within the function's body. However, it seems that nested statements will only get formatted if the top-level statement is included in the range. 

From a user's perspective, I think formatting _anywhere_ isn't really necessary / desirable, but it would greatly improve the usability of range formatting to be able to handle nested statements (though I won't pretend to know how hard it is to support it).

Either way, thanks for hearing me out and for making a fantastic formatter – it's been a huge boon to the Neovim community in particular.

**Comment by JohnnyMorganz** [comment]
Thanks for your comments, great to see it's working well for you and others!

Nested statements should definitely be format-able using range format. This definitely used to be possible, but I've realised I made a change internally changing how nested body's get formatted, meaning nested statements don't work anymore.
I didn't realise it made a change to the range formatting until you mentioned it now, but this part in particular is a bug.

**Comment by mks1508** [comment]
Nothing to do with null-ls... That's how stylua range formatting work ... Actually, stylua range formatting still read whole file content. It just try to format the selected range and ignore others...but it still know if the selected range is nested inside other statment.
