### ISSUE TITLE
parser: unexpected token `goto`

### ISSUE THREAD

**Issue by tami5** [JohnnyMorganz/StyLua#240]
Hello @JohnnyMorganz 

I was trying to format the following file : 

https://github.com/pwntester/octo.nvim/blob/master/lua/octo/model/octo-buffer.lua

but got the following message

```
Could not format file lua/octo/model/octo-buffer.lua: 
error parsing: error occurred while creating ast: 
unexpected token `goto`. (starting from line 171, character 9 and ending on line 171, character 13)
```

Additionally, when I commented that line I got similar error related to `::continue::`

more info https://github.com/pwntester/octo.nvim/pull/193

**Comment by JohnnyMorganz** [comment]
Hey @tami5 

It looks like you have some Lua5.2+ code. How did you install stylua?
If you installed it through cargo, make sure you include `--features lua52`:

```
cargo install stylua --features lua52
```

If you installed through GitHub releases or if this is from the GitHub action, then there may be something else wrong here

**Comment by tami5** [comment]
> Hey @tami5 
> 
> It looks like you have some Lua5.2+ code. How did you install stylua?
> If you installed it through cargo, make sure you include `--features lua52`:
> 
> ```
> cargo install stylua --features lua52
> ```
> 
> If you installed through GitHub releases or if this is from the GitHub action, then there may be something else wrong here

🤨 I don't think neovim is running on lua52, luajit is which as far as I know it's basically lua51. Maybe support this syntax is supported in luajit 🤔. I'm not sure.

**Comment by clason** [comment]
Yes, LuaJIT includes some extensions from Lua 5.2, and in particular `goto` and `::labels::`; see https://luajit.org/extensions.html.

**Comment by tami5** [comment]
Thanks @clason, It would be cool to have a stylua version for luajit.

**Comment by JohnnyMorganz** [comment]
The LuaJIT extensions should be covered in Lua 5.2 mode (mainly the goto and label syntax, which is the same in both).

The only difference is when using `goto` as an identifier - if LuaJIT is built without the `-DLUAJIT_ENABLE_LUA52COMPAT` flag this becomes an issue (as shown in #229) https://luajit.org/extensions.html

In the case you showed though, this isn't an issue. Building with the Lua52 flag will work for your usecase

**Comment by pwntester** [comment]
Thanks @JohnnyMorganz! Can I configure https://github.com/JohnnyMorganz/stylua-action to use the `lua52` flag?

**Comment by JohnnyMorganz** [comment]
> Thanks @JohnnyMorganz! Can I configure https://github.com/JohnnyMorganz/stylua-action to use the `lua52` flag?

It currently has all flags enabled (which hasn't proved a major issue thus far). Running it as-is should work

**Comment by pwntester** [comment]
Going a little bit off-issue (maybe), do you have any idea what can cause [this error](https://github.com/pwntester/octo.nvim/runs/3363139464?check_suite_focus=true) then?

**Comment by JohnnyMorganz** [comment]
> Going a little bit off-issue (maybe), do you have any idea what can cause [this error](https://github.com/pwntester/octo.nvim/runs/3363334511?check_suite_focus=true) then?

Hm, thats a strange one. Let me take a look further

**Comment by JohnnyMorganz** [comment]
> Going a little bit off-issue (maybe), do you have any idea what can cause [this error](https://github.com/pwntester/octo.nvim/runs/3363334511?check_suite_focus=true) then?

Ah, I see the issue. In your `lint.yml` workflow file, you have this: https://github.com/pwntester/octo.nvim/blob/722b6b5985ad52a02017e861a469fa9018dc2a24/.github/workflows/lint.yml#L14
```yml
          args:  stylua --color always --check lua/
```
What this is essentially running is `stylua stylua --color always --check lua/`, so you are passing `stylua` again as an argument - it is trying to format all the files in a "stylua" directory, which doesn't exist!
It should be:
```yml
          args:  --color always --check lua/
```


(Sorry for the delay, got distracted!)

**Comment by pwntester** [comment]
🤦🏼 Thanks a lot, that fixed it!

**Comment by tami5** [comment]
😆 that was my bad, thanks @JohnnyMorganz . I guess this is no longer an issue
