### ISSUE TITLE
Add support to toggle trailing comma in tables

### ISSUE THREAD

**Issue by SilentsReplacement** [JohnnyMorganz/StyLua#246]
Currently, StyLua adds a trailing comma in tables like so:

```lua
local t = {
   1,
   2,
   3, -- trailing comma
```
 
It would be great to toggle this feature through the configuration file. Something like ` table_trailingcomma_add` would do. I want to keep my code consistent and most of my code do not have a trailing comma in tables.

**Comment by JohnnyMorganz** [comment]
As an opinionated formatter, we want to try to keep the number of these stylistic choice options at a minimum (and, at this current point, we most likely won't ever add anymore).

The reason for this is two main things: 1) consistency, and 2) reduce bike shedding [teams arguing which option is better!]

For us, we choose to add in trailing commas to make the diff nicer: having a trailing comma means if you add an extra item later it's not diffing on the previous line. 

[Prettier's stance on this pretty much applies exactly to StyLua too](https://prettier.io/docs/en/option-philosophy.html)

**Comment by LandonSchropp** [comment]
@SilentsReplacement For what it's worth, I'd love to see this option as well. In the Prettier Option Philosophy document, they say:

> A couple [of options] were added after “great demand.” 🤔

I'm not sure what constitutes "great demand", but I can say that the choice to require trailing commas is very polarizing, and having the option to disable it would definitely be appreciated. Prettier includes an option for trailing commas.
