### ISSUE TITLE
Convert `return` -> `return nil` to avoid a gotcha

### ISSUE THREAD

**Issue by ghostnaps** [JohnnyMorganz/StyLua#253]
One of the many gotchas of Lua is that there is a distinction between returning "nothing" and explicitly returning nil. To avoid this gotcha, StyLua could enforce that an empty return statement is converted into `return nil`.

Here's an example of this from the [Roblox Lua Style Guide](https://roblox.github.io/lua-style-guide/gotchas/#returning-nothing):
```lua
local function zero()
    return
end

local function one()
    return nil
end

local a = {1}
table.insert(a, one())  -- Inserting nil leaves a unchanged
table.insert(a, zero())  -- Error! wrong number of arguments to 'insert'
```

Thoughts on implementing this?

**Comment by JohnnyMorganz** [comment]
I'm not sure about altering semantics of code through StyLua, its a very fragile path to go down.
I know for example that [prettier does not touch it at all](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about). Could there be a valid distinction between using one or the other, and forcing returning nil affects that? (I'm not sure myself, but I imagine somewhere out in the wild there is).

Maybe this is more of a job for a linter, such as [selene](https://github.com/Kampfkarren/selene) or luacheck?

**Comment by ghostnaps** [comment]
Good point! Yes this should be a toggleable Selene flag (or similar) instead, rather than something baked into the formatter. Closing this out :)
