### ISSUE TITLE
`--search-parent-directories` not finding config after searching parent

### ISSUE THREAD

**Issue by timbedard** [JohnnyMorganz/StyLua#259]
When a config cannot be found searching the parent directories with `-s`, the config is not found in the alternate config locations (`$XDG_CONFIG_HOME`/`$XDG_CONFIG_HOME/stylua`).

- Version: 0.10.1
- Platform: macOS Big Sur 11.5.2

#### Config at `/Users/tim/.config/stylua.toml` (also tried with `/Users/tim/.config/stylua/stylua.toml`):
```toml
column_width = 88
```
#### Lua file before (at `/Users/tim/example.lua):
```lua
local thisisathing = {this_is_one = "one", this_is_two = "two", this_is_three = "three"}
```

#### Command and output:
```
stylua -sv example.lua

config: starting config search from /Users/tim - recurisvely searching parents: true
config: no configuration file found
config: looking in $HOME/.config/stylua
config: looking in $HOME/.config
config: falling back to default config
config: Config {
    column_width: 120,
    line_endings: Unix,
    indent_type: Tabs,
    indent_width: 4,
    quote_style: AutoPreferDouble,
    no_call_parentheses: false,
}
creating a pool with 8 threads
formatted example.lua in 9.061793ms
```

#### Lua file after:
```lua
local thisisathing = { this_is_one = "one", this_is_two = "two", this_is_three = "three" }
```

#### Expected:
```lua
local thisisathing = {
  this_is_one = "one",
  this_is_two = "two",
  this_is_three = "three",
}
```

Note: It _does_ work with `stylua --config-path=/Users/tim/.config/stylua.toml example.lua`, though #261 then occurs.

**Comment by JohnnyMorganz** [comment]
I think the underlying issue is the same as #260 - so I'm leaning towards saying this is a duplicate? Unless there's something different in these two issues which I haven't seen

**Comment by timbedard** [comment]
> I think the underlying issue is the same as #260 - so I'm leaning towards saying this is a duplicate? Unless there's something different in these two issues which I haven't seen

Yeah, that works for me.
