### ISSUE TITLE
Double quotes preceded by escaped backslash

### ISSUE THREAD

**Issue by KyleMit** [JohnnyMorganz/StyLua#26]
**Input**:

```
local str = '\\"""'
```

**Output**: 

```
local str = "\\"\"\""
```

**Expected**:

```
local str = "\\\"\"\""
```

Preserve the escape on the `\` character and then escape the first double quote since the string has been converted to double quotes.  It would be nice if strings were formatted to [`avoidEscape`s](https://eslint.org/docs/rules/quotes), but for simplicity - forcing into double quotes seems fine too.

**Comment by KyleMit** [comment]
Perhaps a regression of #7 or another issue altogether?

**Comment by JohnnyMorganz** [comment]
Thanks for the report, I'll check it out when I've got some free time! Regarding your latter point, there were various conflicting viewpoints on string quote style when I was discussing this with others, ultimately leading to the decision to keep quotes consistent and forced as double quotes, even if there are escapes within the string (with the idea that, every string will always have a consistent quotation style throughout the codebase, not a mix and match of single and double quotes)

I have a feeling that, for string quotes, this may be one place to allow configuration (still TBD). I would probably have a quote style option or similar, which could select single + double quotes, and also whether to force the type regardless of escapes

**Comment by JohnnyMorganz** [comment]
The original issue here should be fixed as of https://github.com/JohnnyMorganz/StyLua/commit/aed953d7b580037d07e20052dbd52aeb3c0a3dcf. I have opened #28 regarding your latter point about escapes in strings, please feel free to comment your opinion on there (same with anyone else reading this!)
