### ISSUE TITLE
Multiple runs with different output

### ISSUE THREAD

**Issue by timbedard** [JohnnyMorganz/StyLua#261]
Running multiple times on the same file without otherwise changing the file sometimes yields different results.

- Version: 0.10.1
- Platform: macOS Big Sur 11.5.2

#### Config at `/Users/tim/stylua.toml`:
```toml
column_width = 88
```
#### Lua file before (at `/Users/tim/example.lua):
```lua
local thisisathing = {this_is_one = "one", this_is_two = "two", this_is_three = "three"}
```

#### First run:
```
stylua -v example.lua

config: starting config search from /Users/tim - recurisvely searching parents: false
config: Config {
    column_width: 88,
    line_endings: Unix,
    indent_type: Tabs,
    indent_width: 4,
    quote_style: AutoPreferDouble,
    no_call_parentheses: false,
}
creating a pool with 8 threads
formatted example.lua in 1.121355ms
```

```lua
local thisisathing =
	{
		this_is_one = "one",
		this_is_two = "two",
		this_is_three = "three",
	}
```

#### Second run:
```
stylua -v example.lua

config: starting config search from /Users/tim - recurisvely searching parents: false
config: Config {
    column_width: 88,
    line_endings: Unix,
    indent_type: Tabs,
    indent_width: 4,
    quote_style: AutoPreferDouble,
    no_call_parentheses: false,
}
creating a pool with 8 threads
formatted example.lua in 1.314414ms
```

```lua
local thisisathing = {
	this_is_one = "one",
	this_is_two = "two",
	this_is_three = "three",
}
```

#### Expected:
The output of the second run should be the result after the first run, and subsequent runs should result in no changes.

**Comment by zovits** [comment]
Running into this issue where subsequent runs give different results, and it gets caught in a loop where it bounces back and forth between the two states, causing my Github Action check to always fail since StyLua always wants the other.

State 0:
```Lua
local targetCash = { id = "Ben Franklin" }
local targetName = "StyLua_Bug"

local function findMoney()
	for _, existingObject in pairs(workspace:GetChildren()) do
		if
			existingObject:GetAttribute("MoneyID") == targetCash.id
			and existingObject.Name == targetName .. ".money"
		then
			break
		end
	end
end
```
State 1:
```Lua
local targetCash = { id = "Ben Franklin" }
local targetName = "StyLua_Bug"

local function findMoney()
	for _, existingObject in pairs(workspace:GetChildren()) do
		if
			existingObject:GetAttribute("MoneyID") == targetCash.id and existingObject.Name
				== targetName .. ".money"
		then
			break
		end
	end
end
```

If you take either of these and run StyLua, it will flip to the other. Running many times just flips back and forth, never ending.

**Comment by JohnnyMorganz** [comment]
> State 1:
> 
> ```Lua
> 
> local targetCash = { id = "Ben Franklin" }
> 
> local targetName = "StyLua_Bug"
> 
> 
> 
> local function findMoney()
> 
> 	for _, existingObject in pairs(workspace:GetChildren()) do
> 
> 		if
> 
> 			existingObject:GetAttribute("MoneyID") == targetCash.id and existingObject.Name
> 
> 				== targetName .. ".money"
> 
> 		then
> 
> 			break
> 
> 		end
> 
> 	end
> 
> end
> 
> ```
> 
> 
> 

Seems to be the same (incorrect) formatting issue as #257, except in this case it's even worse as it keeps flipping between the two.

In all these cases, I assume it's very near the column width boundary - this probably means we are incorrectly calculating the width budget available on a line somewhere, just need to find out where.
