### ISSUE TITLE
Cleaner breaks for long and/or statements

### ISSUE THREAD

**Issue by archiif** [JohnnyMorganz/StyLua#275]
Right now, this is the way stylua breaks up and/or statements:
```lua
local variable = (
        (main_preferable_data == false) and alternative
        or main_preferable_data[1] + main_preferable_data[2]
    )
local variable = (
        (main_preferable_data == false)
            and cl.get_alternative_data(option_1, option_2)
        or main_preferable_data[1]
    )
```

I think it would look more readable if it is broken up this way (I think the indentation isn't quite right, but this is addressed in my other issue: [#274](https://github.com/JohnnyMorganz/StyLua/issues/274)):
```lua
local variable = (
        (main_preferable_data == false)
        and alternative
        or main_preferable_data[1] + main_preferable_data[2]
    )
local variable = (
        (main_preferable_data == false)
        and cl.get_alternative_data(option_1, option_2)
        or main_preferable_data[1]
    )
```
For reference, this is the same kind of style used by [black](https://github.com/psf/black), which I think looks pretty nice:
```python
variable = (
    (main_preferable_data == False)
    and alternative
    or main_preferable_data[0] + main_preferable_data[1]
)
```

**Comment by JohnnyMorganz** [comment]
Closing this as I don't think this is something we are going to change. If you disagree, feel free to comment.
