### ISSUE TITLE
stylua hangs when num-threads is 1

### ISSUE THREAD

**Issue by slam** [JohnnyMorganz/StyLua#281]
I have a cheap digital ocean droplet with 1 cpu where stylua hangs every time.

After some debugging, I narrowed it down to `num-threads` getting a default of 1 on that instance. Setting `num-threads` to anything > 1 fixes it.

I repro'd it on my mac by setting `num-threads` to 1:

```
❯ stylua --num-threads 1 --verbose null-ls.lua
config: starting config search from /Users/slam/dotfiles/nvim/.config/nvim/lua/custom/plugins - recurisvely searching parents: false
config: looking for config in /Users/slam/dotfiles/nvim/.config/nvim/lua/custom/plugins
config: no configuration file found
config: falling back to default config
config: Config {
    column_width: 120,
    line_endings: Unix,
    indent_type: Tabs,
    indent_width: 4,
    quote_style: AutoPreferDouble,
    no_call_parentheses: false,
}
creating a pool with 1 threads
[hangs forever]
```

**Comment by JohnnyMorganz** [comment]
It looks like we are deadlocking ourselves. I didn't anticipate single threaded running.

At a time, we have at least two jobs running: a "formatter" job which runs for every file (one job per file) which formats the input code, and sends it to a "output" job which takes the output and deals with it accordingly (outputting diffs/content etc.)

If only one thread is available, then we have the "output" job started, but no more threads available in the pool to run a "formatter" job, leading to an infinite hang.

To get around this for the time being, manually setting `--num-threads` to a value >= 2 should work, as you mentioned.
