### ISSUE TITLE
Odd indenting that goes away once ran twice

### ISSUE THREAD

**Issue by Kampfkarren** [JohnnyMorganz/StyLua#290]
```lua
return function()
	call(function()
		local abortSelfPromise = abortSelf(
			function()
				return Promise.resolve(true)
			end,

			function()
				return Promise.new(function(newResolve)
					resolve = newResolve
				end)
			end
		)
	end)
end
```

...gets formatted the first time to:

```lua
return function()
	call(function()
		local abortSelfPromise = abortSelf(function()
			return Promise.resolve(true)
		end, 
function()
			return Promise.new(function(newResolve)
				resolve = newResolve
			end)
		end)
	end)
end
```

...until being replaced with the best result:

```lua
return function()
	call(function()
		local abortSelfPromise = abortSelf(function()
			return Promise.resolve(true)
		end, function()
			return Promise.new(function(newResolve)
				resolve = newResolve
			end)
		end)
	end)
end

```

**Comment by Kampfkarren** [comment]
Another odd style change with multiple functions:

```lua
return function()
	if overrides == nil then
		setupOverrides()
	end

	if overrides[key] == nil then
		return value
	end

	return overrides[key]
end, function(callback)
	overrideWatchers[key] = callback
end
```

...gets formatted into

```lua
	return function()
		if overrides == nil then
			setupOverrides()
		end

		if overrides[key] == nil then
			return value
		end

		return overrides[key]
	end,
		function(callback)
			overrideWatchers[key] = callback
		end
```

**Comment by JohnnyMorganz** [comment]
First example can be narrowed down further into something unrelated to functions:
```lua
local foo = foo(
	foo,

	bar
)
```
seems to be caused by the extra newline in between the arguments

**Comment by JohnnyMorganz** [comment]
> Another odd style change with multiple functions:
> 
> ```lua
> return function()
> 	if overrides == nil then
> 		setupOverrides()
> 	end
> 
> 	if overrides[key] == nil then
> 		return value
> 	end
> 
> 	return overrides[key]
> end, function(callback)
> 	overrideWatchers[key] = callback
> end
> ```
> 
> ...gets formatted into
> 
> ```lua
> return function()
> 	if overrides == nil then
> 		setupOverrides()
> 	end
> 
> 	if overrides[key] == nil then
> 		return value
> 	end
> 
> 	return overrides[key]
> end,
> 	function(callback)
> 		overrideWatchers[key] = callback
> 	end
> ```

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/StyLua/issues/290#issuecomment-962892439 going to open another issue for this - as its unrelated to the current issue, and theres a bit more to it
