### ISSUE TITLE
Removes significant whitespace in table keys

### ISSUE THREAD

**Issue by josa42** [JohnnyMorganz/StyLua#293]
In some cases stylua removes significant whitespace around strings which are enclosed by `[[` and `]]`.

For **example**

```lua
local map = {
  [ [['test']] ] = 'test',
}

print(map[ [['test']] ])
```

After running stylua against it the spaces around `[['test']]` are removed...

![image](https://user-images.githubusercontent.com/423234/140966495-656093b6-88d2-4ad1-abce-d667c736d220.png)

... which leads to invalid lua code:

```lua
local map = {
  [[['test']]] = 'test',
}

print(map[[['test']]])
```

**Comment by JohnnyMorganz** [comment]
Interesting, I didn't realise this was possible - thanks for pointing it out!

**Comment by josa42** [comment]
@JohnnyMorganz WOW that was quick! Thanks so much!

**Comment by JohnnyMorganz** [comment]
This is fixed in the newest release: https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.11.2
