### ISSUE TITLE
HomeBrew Install Fails: brew install stylua

### ISSUE THREAD

**Issue by johnrm9** [JohnnyMorganz/StyLua#306]
brew install stylua
==> Downloading https://ghcr.io/v2/homebrew/core/stylua/manifests/0.11.2
curl: (22) The requested URL returned error: 404

Error: stylua: Failed to download resource "stylua_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/stylua/manifests/0.11.2

**Comment by JohnnyMorganz** [comment]
I don't really know about homebrew, I think it's managed by @clason, maybe they can give an insight?

**Comment by clason** [comment]
You just tried too quickly -- the formula was upgraded, but the new bottle wasn't uploaded yet. It works now.
