### ISSUE TITLE
Deal properly with comments in unusual places

### ISSUE THREAD

**Issue by appgurueu** [JohnnyMorganz/StyLua#307]
I like to comment my functions as follows:

```lua
function func(
	param_a -- description of a
	, param_b -- description of b
) end
```

StyLua turns this into the following:

```lua
function func(
	param_a -- description of a,
	param_b -- description of b
) end
```

Which is incorrect (a syntax error) as the comma is moved inside the comment. Lua 5.1 - 5.4 as well as LuaJIT all support such comments as they are filtered out in a tokenization step; poor syntax highlighters like GitHub's unfortunately don't.

**Comment by JohnnyMorganz** [comment]
Similar bug with function call syntax:
```lua
call(param_a -- nice param
, param_b)
