### ISSUE TITLE
Normalize between `function NAME()` and `NAME = function()`

### ISSUE THREAD

**Issue by IndianBoy42** [JohnnyMorganz/StyLua#308]
As far as I know they are equivalent syntax, I wonder if stylua should enforce using one consistently?

```lua
GLOBAL = function() <-> function GLOBAL() 
local name = function() <-> local function name()
Object.name = function() <-> function Object.name()
```

My first instinct is to use the name between function and arguments form always. But using the former makes it easier to move code to and from places that take anonymous functions

Like these refactorings are easier done (by hand) if we use 'anonymous' functions always:
```lua
local cb = function() end
function_that_takes_a_callback(cb)
<->
function_that_takes_a_callback(function() end)

local cb = function() end
local table = {
    cb = cb,
}
<->
local table = {
    cb = function() end,
}
```

**Comment by GlowingUmbreon** [comment]
There some cases where using one over the other is useful, a simple example is something like this
```lua
local func 
if DEBUG then
   func = function()
      print("a")
   end
else
   func = function()
      print("b")
   end
end

func()
```

**Comment by IndianBoy42** [comment]
That seems like related to my argument that we should always use anonymous functions and assignments. 

Where does the more traditional named function syntax make more sense?

**Comment by GlowingUmbreon** [comment]
> That seems like related to my argument that we should always use anonymous functions and assignments.
> 
> Where does the more traditional named function syntax make more sense?

I believe that 1 looks better than 2, but there are some situations where 2 may be necessary.
1)
```
local function waffles()

end
```
2)
```
local waffles = function()

end
```

**Comment by JohnnyMorganz** [comment]
I think its unlikely that we will be normalising function syntax like this. There are cases where the assignment syntax may be necessary, as mentioned above, but also I think the name-function syntax is better for normal definitions (and it is also what is [recommended by the style guide we follow](https://roblox.github.io/lua-style-guide/#functions)).
