### ISSUE TITLE
AutoPreferSingle not behaving as expected

### ISSUE THREAD

**Issue by nwithers-ecr** [JohnnyMorganz/StyLua#311]
I am using Stylua to format my neovim config files and I've run into a case where I believe it's behaving incorrectly as described. 

The documentation says that
```
we prefer the quote type specified, but fall back to the opposite if it leads to fewer escapes in the string.
```
However, with this example
```lua
vim.api.nvim_set_keymap('n', '<Leader>be', "<cmd>echo system('base64', @\")<CR>", opts)
```
running the command
```
stylua --check --indent-type Spaces --indent-width 2 --line-endings Unix --quote-style AutoPreferSingle test.lua
```

produces no output, when it should be producing the below in order to remove the escape.

```lua
vim.api.nvim_set_keymap('n', '<Leader>be', '<cmd>echo system("base64", @")<CR>', opts)
```

**Comment by JohnnyMorganz** [comment]
StyLua only changes the quote type for the actual string. It will not change quotes contained within the string, only escape these quotes as necessary.

Escaping quotes within a string doesn't make an overall difference, but if we change quotes, it is no longer the same string

```
print("\"" == '"') -- true
print("\"" == "'") -- false
```

If we did the change you are expecting (i.e. change `'base64'` to `"base64"`), the output string is no longer the same. This can lead to unintended consequences.

At most, we would do
```lua
vim.api.nvim_set_keymap('n', '<Leader>be', '<cmd>echo system(\'base64\', @")<CR>', opts)
```
but this doesn't lead to fewer escapes

**Comment by nwithers-ecr** [comment]
That makes sense, thanks.
