### ISSUE TITLE
Output `--check` to another diff tool

### ISSUE THREAD

**Issue by nwithers-ecr** [JohnnyMorganz/StyLua#312]
This is related to #230

I already have [a diff tool](https://github.com/dandavison/delta) with my ideal configuration options predefined. It would be nice if `--check' could use that one instead.

**Comment by nwithers-ecr** [comment]
Something like this does work but it's ugly
```
delta test.lua - < <(stylua --check \
                            --indent-type Spaces \
                            --indent-width 2 \
                            --line-endings Unix \
                            --quote-style AutoPreferSingle test.lua)
```

**Comment by JohnnyMorganz** [comment]
I think this can just be housed within #230. If we could output a unified format, you could then do `stylua --check --output unified test.lua | delta`.

**Comment by JohnnyMorganz** [comment]
Closing this in favour of #230, because that's essentially what this is

**Comment by JohnnyMorganz** [comment]
This is now supported in v0.13.0: https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.13.0
