### ISSUE TITLE
leave line with original hanging if inlining fails

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#314]
This code:
```lua
local popupMenuText = {"Featured", "Friend Activity", "My Recent", "Popular",
	"Popular Near You", "Recommended", "Top Earning", "Top Rated"}
```
became this code:
```lua
local popupMenuText = {
	"Featured",
	"Friend Activity",
	"My Recent",
	"Popular",
	"Popular Near You",
	"Recommended",
	"Top Earning",
	"Top Rated",
}
```

and I'm wondering why it didn't just bail on inlining the table initializer once it wouldn't fit within the line budget, and only put spaces around the braces.

**Comment by LastTalon** [comment]
This formatting seems correct to me.

**Comment by JohnnyMorganz** [comment]
Yeah, I'm not too sure about leaving it as-is, the current formatting looks right (and is also [what prettier does](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHC2Cu2AsgvgCpwAeWAvJgNoA6IAYnAIYz4BOcAJswA0mZi24BLBH0wBBMDHEA3cTACeQkSCKrMAJThgEMDcwAKefABt23IYyiNjIcwWvdMAOQ7uAmhHwmIPqQALYhUvyBZHiYAKI2UOJQAOZRMbqckSAAuiCCIHgK6MigNtwQAO6mNghoyCDslhXsqnX5AEbc7GAA1nAwAMrs4QAySXDIAGaNaHAdXb39A9jdScnIMNz4cyBwIe38fPwj7Cn47MlwLBDcIZwKKfXs+DAQeSAAFjAhlgDqHyo4GgVoYBrUVEoVKp6mA0G0QElZtwYKYusk7lMZjsAFZoSgDNaWOAARXwEHgmMss3yK24SPq7XYB0s72wElgv3EfBgH2QAA4AAw08qzX5dbD1NlAuDcRQTfIARzJ8FReDqKHYaAAtFA4Px+O9eErxLxURcMUhplSdrMQuINlsbYSScqJpasfkYEzOdzeUgAEyerriSxrADCEDC7HqQIArO98LMyEz1VbqSBFNsAJJQI6wAZgCTYGAyXMDNREymzAC+1aAA))

**Comment by matthargett** [comment]
I looked into the prettier code and its history and reported issues, and agree that this leaves code in a more consistent state than an arbitrary break that doesn't require alignment for inline comments. cc @MagiMaster
