### ISSUE TITLE
Comments in unusual locations of a table lead to syntax errors

### ISSUE THREAD

**Issue by idbrii** [JohnnyMorganz/StyLua#318]
Similar to #23 and #307, comments inside a table definition makes stylua create invalid syntax:

    local a = {
        b =  -- a comment breaks it
        {
            c = "d",
        },
    }

becomes

    local a = {
        b =  -- a comment breaks it{
            c = "d",
        },
    }

Tested on [v0.11.2](https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.11.2)

**Comment by JohnnyMorganz** [comment]
Hm, where would you stick the comment in this situation? I just quickly [stuck it into prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTYAHSkzMwCNMkyB6WnTSAW2YSwoCc5sBrAZ0wBLGCXKEx48mGqYiIACbyANJLIBfVVHUhlICAAcYQ6P2ShsnThADuABUsIzKbKhvYAnmb1dsYXhgAythsADJCUHDIAGau-HA+nH4BMIEGfhEA5sgwnACuCSBwzBRwCgplodhQmXnYmXAAYhCczNgwxjXIINh5MBC6IAAWMMyoAOpDInD86WBwgU4iQgBuIh7dYPzeIBHxnDB2SZltMXGFAFb8AB6BWegAinkQ8Geo8XrpnPvdFNilqEGBk4ERg4yEChgQ2QAA4AAyfazxcZJAzdYEzOCcFZRPQAR2e8COhmcPX4AFpImUyoNuAShNwjvVTkhYu9CvFmEIcvkOfc4E8XlFWec9DB-uDIdCkAAmMVJISoLIAYQgrGw3RmAFZBnl4gAVf7ONkfEArAoASSgFVggTAIKMAEFrYEYB50G94up1EA) and I see that for JavaScript they just stick the comment before the `b =` line - probably the easiest place to put it

**Comment by idbrii** [comment]
I would expect it to be on the same line because I'd expect comments to be mostly invisible to the prettifier and more in line with :

    local a = {
        b = { -- a comment breaks it
            c = "d",
        },
    }

But, yeah doing it on the same line also seems reasonable:

    local a = {
        -- a comment breaks it
        b = {
            c = "d",
        },
    }


Looks like [luacheck comments](https://luacheck.readthedocs.io/en/stable/inline.html) are all start of line -- that's the main thing I'd expect to break if you moved the comment.

**Comment by JohnnyMorganz** [comment]
Yeah, I'll probably stick it on the line above, because that's the simplest way to do it currently.
Hopefully I'll get time today to sort it out and publish a new release
