### ISSUE TITLE
unable to format goto with local in loop

### ISSUE THREAD

**Issue by danpf** [JohnnyMorganz/StyLua#324]
```
$ stylua -V 
stylua 0.11.2
```

test.lua
```
for x = 1, 10 do
	if x == 5 then
		goto continue
	end
	print("x: " .. x)
    local c = 0

	::continue::

    local pos = 9
end
```

```
$ stylua test.lua
error: could not format file test.lua: error parsing: unexpected token `local`. (starting from line 10, character 5 and ending on line 10, character 10)
additional information: expected identifier after `::`
```

**Comment by JohnnyMorganz** [comment]
Looks like the same issue as https://github.com/JohnnyMorganz/StyLua/issues/309, how did you install stylua?

If you can, try with `cargo install stylua --features lua52` and see if that works

**Comment by danpf** [comment]
I just downloaded it from the releases page. I was avoiding installing cargo since I don't use it but I can look into it now I guess

**Comment by JohnnyMorganz** [comment]
> I just downloaded it from the releases page. I was avoiding installing cargo since I don't use it but I can look into it now I guess

Yep, I definitely want to get it available as a prebuilt binary on the releases page again. Hopefully sometime soon. Apologies for the inconvenience

**Comment by danpf** [comment]
That's totally fine thank you for your work on this project -- it's really appreciated!
