### ISSUE TITLE
Formatting breaks some property in lua file

### ISSUE THREAD

**Issue by touhidulShawan** [JohnnyMorganz/StyLua#325]
Formatting breaks some property in awesome window manager configuration file. When I edit my config file `rc.lua` with neovim it breaks some property on my config file like `ontop` -> `on top`
What should I do? Is there something wrong?

**Comment by JohnnyMorganz** [comment]
Do you mind pasting the snippet of/giving me a link to the code in question? So that I can test it myself to see the issue

**Comment by touhidulShawan** [comment]
[rc.lua](https://github.com/touhidulShawan/awesome/blob/master/rc.lua)

**Comment by touhidulShawan** [comment]
@JohnnyMorganz if you have time please check on it

**Comment by JohnnyMorganz** [comment]
I tried running stylua on the rc.lua file you provided, but I did not find any issue and the file seems to still parse fine (I did not see `ontop` changing to `on top` anywhere either).
Can you explain the specific thing which is breaking, maybe with a before and after code snippet? I haven't used awesomewm before so I don't know how the configuration should be.

**Comment by touhidulShawan** [comment]
I apologize for my mistake. With null-ls-nvim I am also using codespell with it's default config option. This causes the automatic correction of misspelled word that's why `ontop` becomes `on top` while I format rc.lua file. I have just figured out the causes. Sorry for my mistake.
