### ISSUE TITLE
Hang expressions within a function call if necessary

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#34]
There are situations where codebases have strings concatenated together so that they can push them onto multiple lines, to improve the readability.
For example:
```lua
local longString = foo(
     "We are wrapping this %s "
    .. "onto multiple lines "
    .. "for ease of editing and %d readability", 
    myStringVar, 
    myNumberVar
)
```
We should keep them expanded if that is the case (with the similar logic as to what we do with already expanded tables)

**Comment by KyleMit** [comment]
I think this has already been resolved for variable declarations and return statements. Still happening when the multiline expression occurs inside of a function call

```lua
local var = "long line something something 1" .. "long line something something 2" .. "long line something something 3"

local function hello(val)
	return "long line something something 1" .. "long line something something 2" .. "long line something something 3" .. val
end

hello("long line something something 1" .. "long line something something 2" .. "long line something something 3")
```

**Comment by JohnnyMorganz** [comment]
Its common that function calls will contain anonymous functions within them (this is present in one of our large example tests). I therefore want to get #33 before this will be added - #33 however is quite a big change, so it may take a while depending on how busy I am
