### ISSUE TITLE
^M on every line

### ISSUE THREAD

**Issue by ffuszthaler** [JohnnyMorganz/StyLua#365]
![image](https://user-images.githubusercontent.com/25418250/153243686-d851838d-b83d-4850-b71b-be852130f4d2.png)
 
I'm on Windows 10
I get this everytime I use stylua through null-ls inside neovim, regardless if I change line_ending to "Windows"
Am I doing something wrong?

**Comment by JohnnyMorganz** [comment]
`^M` indicates a CRLF (Windows) line ending, if I'm not mistaken?

Is this not what is intended?

**Comment by ffuszthaler** [comment]
Yeah, but why do they show up now (only after I use stylua, shouldn't they have been always there), can I change that

**Comment by JohnnyMorganz** [comment]
I'm not really a Neovim user, so I don't know unfortunately.

I'll test it out though on my side to see if anything weird is happening with stylua and CRLF line endings

**Comment by ffuszthaler** [comment]
Also if you don't use Neovim what do you in combination with Stylua?

**Comment by ffuszthaler** [comment]
ok, seems to happen with prettier aswell

**Comment by ffuszthaler** [comment]
Ok, seems to happen with every formatter
I tried it with prettier and regardless of what --end-of-line (lf|crlf|cr|auto) was set to
^M showed up

**Comment by JohnnyMorganz** [comment]
> Also if you don't use Neovim what do you use in combination with Stylua?

StyLua originally spawned to automate the style guide at Roblox (https://roblox.github.io/lua-style-guide/) and in Roblox-based codebases. I personally just use it for any Lua codebases (such as Luvit or Neovim too)



> Ok, seems to happen with every formatter
> I tried it with prettier and regardless of what --end-of-line (lf|crlf|cr|auto) was set to
> ^M showed up

So, would you say that this is not a bug? I haven't experimented myself yet but I will try to do so over the weekend

**Comment by ffuszthaler** [comment]
Don't think so, but it is probably a good idea if you also check for yourself
