### ISSUE TITLE
Block ignore is not applied to all back-to-back blocks

### ISSUE THREAD

**Issue by echasnovski** [JohnnyMorganz/StyLua#421]
When `--stylua: ignore start/end` comments are applied back-to-back, they take effect on every second ignored block. This might be considered as a non-issue because they can be merged into one single ignored block, but it might be inconvenient when they are separated with large comment block.

My understanding is that "this comment must be preceding a statement (same as `-- stylua: ignore`), and cannot cross block scope boundaries" holds here, although I am not sure about it.

Steps to reproduce:
- Create file `tmp.lua` with the following contents:
```lua
--stylua: ignore start
local a   =   1
--stylua: ignore end

--stylua: ignore start
local b   =   2
--stylua: ignore end

--stylua: ignore start
local c   =   3
--stylua: ignore end

-- Some very large comment

--stylua: ignore start
local d   =   4
--stylua: ignore end
```
- Run `stylua tmp.lua`.

Currently observed output:
```lua
--stylua: ignore start
local a   =   1
--stylua: ignore end

--stylua: ignore start
local b = 2
--stylua: ignore end

--stylua: ignore start
local c   =   3
--stylua: ignore end

-- Some very large comment

--stylua: ignore start
local d = 4
--stylua: ignore end
```

Details:
- Version of StyLua: 0.12.5
- OS: Xubuntu 20.04.

**Comment by JohnnyMorganz** [comment]
Yeah, this is a bug - it seems as though we are not correctly re-opening an ignore section when we see the `--stylua: ignore start` comment.

This code is actually parsed as these separate statements:
```lua
--stylua: ignore start
local a   =   1
---------------------------
--stylua: ignore end

--stylua: ignore start
local b   =   2
```
where `--stylua: ignore end` and `--stylua: ignore start` are both leading trivia of the `local b` statement.
We are probably exiting early when we see the `--stylua: ignore end` comment in the leading trivia, but we should continue scanning in case we find another ignore comment afterwards
