### ISSUE TITLE
Oh It have  some problem after I run `stylua mycode.lua`  ,insert `III` in mycode.lua file.

### ISSUE THREAD

**Issue by sober-wang** [JohnnyMorganz/StyLua#438]
![image](https://user-images.githubusercontent.com/35804630/162411753-a8341d5a-f2d6-4535-9271-ff1d90a92e97.png)

**Comment by JohnnyMorganz** [comment]
I'm not entirely sure what this is - this looks like neovim, could the `III` be displaying an indentation?
This looks more like a neovim issue than a stylua one - is the actual file malformed?

**Comment by JohnnyMorganz** [comment]
Going to close this as this seems like an editor issue, not about stylua.
If you have further info happy to look into it further
