### ISSUE TITLE
unexpected token `type`

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#45]
On current main (hash d8700875dcb4d61772987d8f27f49d3741113537), in a file where I have 
```lua
type Array<T> = { [number]: T }
```

I get this error:
```
error: could not format file definition.lua: error parsing: error occurred while creating ast: unexpected token `type`. (starting from line 30, character 1 and ending on line 31, character 5)
additional information: leftover token
```

It would be nice if it would skip that AST parent node and proceed, rather than erroring.

**Comment by JohnnyMorganz** [comment]
Hey @matthargett, this seems like Luau syntax, which we should be supporting.

Did you build the tool locally/download it from cargo? If so, you need to indicate `--features luau` to build with Luau syntax

**Comment by KyleMit** [comment]
Thanks @JohnnyMorganz / @matthargett - Confirmed both tickets work when compiled with `--features lua`
