### ISSUE TITLE
fail on cargo install stylua via docs

### ISSUE THREAD

**Issue by charlesmilam** [JohnnyMorganz/StyLua#461]
↪ cargo install stylua
    Updating crates.io index
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository: ssh://git@github.com/rust-lang/crates.io-index

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  error authenticating: no auth sock variable; class=Ssh (23)

**Comment by JohnnyMorganz** [comment]
This looks like an issue with cargo. Unfortunately I don't know much about this error to help, but there may be some debugging steps available online

Alternatively, you can download a prebuilt binary over at https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.13.1 and stick it on your PATH
