### ISSUE TITLE
Question about Configuration Options

### ISSUE THREAD

**Issue by Stanzilla** [JohnnyMorganz/StyLua#48]
Hey there! I know you said this is very opinionated but I was wondering which configuration options you are going to/willing to add in the future. I'm very interested in using this as a replacement for LuaFormatter which does allow the following https://github.com/Koihik/LuaFormatter#default-configuration

**Comment by JohnnyMorganz** [comment]
Hey there, thanks for the interest in StyLua!

I feel as though, in regards to configuration options, I do not wish to add too many. The project was originally inspired by Prettier, and I feel as though their range of options (where applicable to Lua) are a reasonable set personally (but they do regret some of them, as explained [here](https://prettier.io/docs/en/option-philosophy.html))

That being said, I am happy to facilitate discussion around specific formatting points, and if there's a style which is common in a lot of places, I'm happy to think about supporting it. This *might* lead on to add a configuration if the general consensus agrees (see #28 - there was a further discussion off GitHub too), but I'll be hesitant at first.

Do you mind explaining specifically the configuration you use from LuaFormatter that you would like to see in StyLua?

**Comment by JohnnyMorganz** [comment]
Oh, and a point to mention, I follow the [Roblox Lua Style Guide](https://roblox.github.io/lua-style-guide) when implementing the style choices, so it would be unlikely that anything going against that would be supported. But again, I'm happy for discussion.

**Comment by Stanzilla** [comment]
Ah so I just tested it on a file and noticed these things:

- Quote style (you are already working on this)
- max line length

Assuming break ups like these are line length related?

![image](https://user-images.githubusercontent.com/75278/107088825-dbfb5300-67fd-11eb-9527-cc17da0b22b6.png)

and then possible the comma placement for these

![image](https://user-images.githubusercontent.com/75278/107088946-1369ff80-67fe-11eb-84c1-ae7712a689f2.png)

**Comment by JohnnyMorganz** [comment]
Quote Style - yeah, there was some discussion here, and I'll probably add it in (feel free to react with your support on #28 just so I have a better indication)

Line length - this is actually all over the place inside of the codebase right now, as there isn't a single best way to do this with the current way everything has set up (see, #5). Its all based on best-guess heuristics at the moment. I know Prettier has a configuration option here, and I think I can agree on this case to add an option too.

From your screenshots, was this the ouput of StyLua or LuaFormatter? In the first screenshot, you're right in saying that's line length related. The second one though, that doesn't look like StyLua output - are you saying the addition is how you would've liked it to be laid out?

**Comment by Stanzilla** [comment]
that's Stylua output from a codebase that did not use any auto formatter before

**Comment by JohnnyMorganz** [comment]
Hm I just tested that now, and that is not what I was expecting (I thought StyLua would actually just stick it on one big line, which in itself isn't great either). 

For the second screenshot, I would agree that what you had originally would actually be the best style here - feel free to open up a separate issue for this, and I can check it out soon.

**Comment by JohnnyMorganz** [comment]
I will be closing this issue - to track the column width setting, see #5, and for quotation style, see #28.
If you have any further questions/bugs to report, feel free to open a new issue
