### ISSUE TITLE
Provide a way to format a `full_moon::ast::Ast` directly

### ISSUE THREAD

**Issue by philpax** [JohnnyMorganz/StyLua#482]
Hi there! I'm generating Lua with `full_moon`, and would like to format the generated Lua using `stylua_lib` without having to re-parse it. Looking at the code for `stylua_lib::format_code`, this looks like it should be relatively trivial (e.g. a wrapper around `formatters::CodeFormatter::new(config, range).format(input_ast)`), but `formatters` is private to external users.

For now, I'm happy to just re-parse my generated code, but I'd like to avoid the intermediary step at some point 🙂

**Comment by JohnnyMorganz** [comment]
Sounds reasonable to me 👍
Haven't really had any library consumers yet, so if anything isn't very ergonomic, do let me know!

**Comment by JohnnyMorganz** [comment]
> Awesome, thank you! Is a new release far off, or should I switch to a Git dependency?

Hoping for a new release in the next few days, once the 2 open PRs are merged - just testing for any issues right now

**Comment by philpax** [comment]
Just updated to 0.14.0 and can confirm this works as expected, thanks again!
