### ISSUE TITLE
Issue with very long lines of variable declarations

### ISSUE THREAD

**Issue by Stanzilla** [JohnnyMorganz/StyLua#49]
Continued from https://github.com/JohnnyMorganz/StyLua/issues/48#issuecomment-774287677

Issue is ![image](https://user-images.githubusercontent.com/75278/107088946-1369ff80-67fe-11eb-84c1-ae7712a689f2.png) looks a bit awkward

**Comment by JohnnyMorganz** [comment]
The original bug here has been fixed in https://github.com/JohnnyMorganz/StyLua/commit/4ff5dbbda005661e1246b07ffcd29a298402a87b - however, this isn't the most optimal formatting. I have opened a new issue #62 to deal with improving the formatting
