### ISSUE TITLE
Don't collapse function body if it would expand function call args

### ISSUE THREAD

**Issue by mhanberg** [JohnnyMorganz/StyLua#493]
Hi!

I was excited to see #479 get merged and I am trying it out. I noticed a case where (IMO) the formatted code seems less readable than it was before.

## Before

```lua
function M.code_action_listener()
  local context = { diagnostics = vim.lsp.diagnostic.get_line_diagnostics() }
  local params = lsp_util.make_range_params()
  params.context = context
  vim.lsp.buf_request(0, 'textDocument/codeAction', params, function(err, _, result)
    print("code action here"..vim.inspect(result))
  end)
end
```

## After

```lua
function M.code_action_listener()
  local context = { diagnostics = vim.lsp.diagnostic.get_line_diagnostics() }
  local params = lsp_util.make_range_params()
  params.context = context
  vim.lsp.buf_request(
    0,
    "textDocument/codeAction",
    params,
    function(err, _, result) print("code action here" .. vim.inspect(result)) end
  )
end
```

I assume this has to do with collapsing the function, then it hitting max line length, then moving each arg onto it's own line. I feel like this shouldn't be the case.

Thanks for the library and let me know what you think of this issue.

**Comment by JohnnyMorganz** [comment]
Even with the collapse option disabled, to be honest I would lean more towards after + expanded function body there.

This is what stylua used to do, but there are reasons why it doesn't anymore. Some disccusion in https://github.com/JohnnyMorganz/StyLua/issues/276 about it

I think I will probably leave the After as-is for now, sorry.
