### ISSUE TITLE
Use column width as a bigger indicator when to split lines

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#5]
Currently, the formatted chooses to split lines by determining the number of bytes between the contained span braces (for TableConstructor and FunctionArgs). 
This isn't great, as it doesn't take into account the current column width (e.g. if we are a few indents deep)

Column width should be used as the deciding factor about when to introduce line breaks (need to find a way to calculate this as the formatters currently "don't know about their surroundings")

**Comment by LastTalon** [comment]
Lots of comments I would make about other formatting choices ultimately relate back to this issue, lots of times things are being wrapped/not wrapped irrespective of the width I would typically wrap them at.

I also think the particular column width is something that has good configuration potential, similar to tabs and line endings.
