### ISSUE TITLE
Trailing comments of a semicolon are lost

### ISSUE THREAD

**Issue by Stanzilla** [JohnnyMorganz/StyLua#50]
![image](https://user-images.githubusercontent.com/75278/107108226-a45ccd00-6836-11eb-9880-a1859c0cfd59.png)

bug or feature? :)

**Comment by JohnnyMorganz** [comment]
Definitely not a feature..., but it looks like this is actually a limitation with full-moon. I currently can't access the semicolon token to retrieve the comments, so it's lost (I'll make an issue over there).

A temporary workaround here would be to remove the semicolon manually and it should resolve itself.
