### ISSUE TITLE
stylua.toml in parent directory is ignored when running on a single file

### ISSUE THREAD

**Issue by WhyNotHugo** [JohnnyMorganz/StyLua#503]
I have my config in `~/.config/nvim/stylua.toml `. When I format the file `~/.config.nvim/lua/lsp.lua`, the config is ignored.

I have a symlink to the `stylua.toml` file inside the `lua` directory as a workaround, but ideally, `stylua` should look for a config file in the parent directory -- and probably continue traversing at least until the root of the repo (if any).

**Comment by JohnnyMorganz** [comment]
Do you pass `--search-parent-directories` when running? https://github.com/JohnnyMorganz/StyLua#finding-the-configuration

Note the warning about why this is not enabled by default: recursively searching upwards is not ideal as formatting between different developers can become inconsistent if we use a config file high up in the file tree and the user doesn't realise

**Comment by WhyNotHugo** [comment]
Oh, my bad, totally missed that. I see two somewhat contradictory details:

> Note: enabling searching outside of the current directory is NOT recommended due to possibilities of conflicting formatting:

> It is recommended to keep a .stylua.toml file in your project root so that other developers can make use of the same configuration.

If I do this, it won't be found when editing files in subdirectories of the repo; I actually have to keep a `stylua.toml` in each directory that has lua files, not in the root of the project, right?

**Comment by JohnnyMorganz** [comment]
> If I do this, it won't be found when editing files in subdirectories of the repo; I actually have to keep a stylua.toml in each directory that has lua files, not in the root of the project, right?

Typically it's expected that you are also running stylua at your project root. i.e.

```
root> stylua path/to/file.lua
```
rather than
```
root/path/to> stylua file.lua
```

**Comment by WhyNotHugo** [comment]
I'll keep that in mind. Thanks for the help!
