### ISSUE TITLE
How to get stdout?

### ISSUE THREAD

**Issue by glepnir** [JohnnyMorganz/StyLua#507]
use `spawn` with `stylua filename` .looks like this way I can't get stdout

**Comment by JohnnyMorganz** [comment]
Sorry, you will need to provide more info. What are you using this with, and what code are you running?

**Comment by glepnir** [comment]
just like 

```lua
  self.handle, self.pid = uv.spawn('spawn', {
    args = { filename },
    stdio = { stdin, stdout, stderr },
  }, function(_, _)
    uv.read_stop(stdout)
    uv.read_stop(stderr)
    safe_close(self.handle)
    safe_close(stdout)
    safe_close(stderr)
  end)

  uv.read_start(
    stdout,
    function(err, data)
      print(data)
    end)
  )

```

**Comment by MunifTanjim** [comment]
`stylua` by default writes the file in-place. If you run `cat filename | stylua -`, only then it'll print out the output to `stdout`.

---

In contrast, prettier prints out the output to `stdout` by default. And it will only write the file in-place if `-w` flag is provided:

```
  -w, --write              Edit files in-place. (Beware!)
```

**Comment by JohnnyMorganz** [comment]
> Thinking about it, prettier's behavior seems safer and convenient for writing integrations (like the one in example above).

I think I agree, but its too late to change that now...

**Comment by glepnir** [comment]
yup i usually use `stylue  filename` to format now I want save file then run format in neovim by spawn . `print data ` is nil.

**Comment by JohnnyMorganz** [comment]
Unfortunately, that is not something we can really solve, as this looks specific to your code, and whatever `uv.spawn` is (looks like luv)

At a glance, instead of `cat filename | stylua -`, you can just run `stylua -` directly, and pass in the code through stdin:

```lua
self.handle, self.pid = uv.spawn('stylua', {
    args = { '-' },
    stdio = { stdin, stdout, stderr },
  }, function(_, _)
     -- .. your code
end)

uv.write(stdin, "local   x    =   1") -- replace the lua code here with however you retrieve file contents

-- .. the rest of your code
```

**Comment by MunifTanjim** [comment]
> Unfortunately, that is not something we can really solve

Can we maybe consider a flag like `--print` or `--dry` that just outputs the formatted code instead of writing the file? 🤔

**Comment by JohnnyMorganz** [comment]
> > Unfortunately, that is not something we can really solve
> 
> ~Can we maybe consider a flag like `--print` or `--dry` that just outputs the formatted code instead of writing the file?~ 🤔
> 
> nvm. Adding that flag would imply it's turned on by default for `stylua -`. That might cause confusion.

The reason why I haven't yet come up with a flag for this is because I never decided on a way to structure the output, especially for multiple files.

We need a separator in the output (do we want that machine readable?).

We can tack on a new option to `--output`, and instead users can run

```sh
$ stylua --check --output=formatted path/to/file.lua
```

**Comment by JohnnyMorganz** [comment]
Marking as complete, if you have any more questions, feel free to mention

**Comment by glepnir** [comment]
so current way is use `stylua -` then pass code to `stdin` right?

**Comment by JohnnyMorganz** [comment]
> so current way is use `stylua -` then pass code to `stdin` right?

Correct

**Comment by glepnir** [comment]
If using this way, I need to iterate through the lines of the whole file and pass them to stdin, maybe we can improve this way in the next version. Like said above we should provide an option?

**Comment by JohnnyMorganz** [comment]
> If using this way, I need to iterate through the lines of the whole file and pass them to stdin, maybe we can improve this way in the next version. Like said above we should provide an option?

You don't need to iterate through the lines, I would assume there is a function to read all lines into a buffer, then pass that into stdin.

Option is reasonable though
