### ISSUE TITLE
reversability issue in inspect.lua from luvit

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#514]
https://github.com/kikito/inspect.lua/blob/master/inspect.lua

reduction:
```lua
local function escape(str)
	return (str:gsub("\\", "\\\\"):gsub("(%c)%f[0-9]", longControlCharEscapes):gsub("%c", shortControlCharEscapes))
end
```

with a 100 column width limit, running stylua 0.14.2 on the file twice has an effect. without the 100 column limit (defaulting to 120), it also has unstable formatting on the second format, but it doesn't reverse like it does at the 100 column limit.

**Comment by JohnnyMorganz** [comment]
A few other related issues: https://github.com/JohnnyMorganz/StyLua/pull/546#issuecomment-1221537541
