### ISSUE TITLE
stylua.styluaPath extension setting results in "new update" popups

### ISSUE THREAD

**Issue by TreehouseFalcon** [JohnnyMorganz/StyLua#515]
I installed the StyLua VSCode extension and have set the `stylua.styluaPath` setting to my version installed with Foreman. It's located in my C:\Users\___\.foreman\bin folder. It functions perfectly, but every time I change an extension setting or relaunch VSCode with the setting pointing to my local Foreman copy of StyLua, I get the attached popup message. No popup appears if the `stylua.styluaPath` is not set, and an error message appears if the styluaPath is pointing to an invalid file.

The version of StyLua I have installed with Foreman is v0.14.2. This is the same version it's prompting me to upgrade to.

![image](https://user-images.githubusercontent.com/56169608/181618901-b8f33fdf-d7c1-486d-96ec-02e5b05039c5.png)

**Comment by LastTalon** [comment]
If you run the full path you have with the option `-V` what is the version it provides?

**Comment by TreeHouseFalcon** [comment]
It gives me `stylua v0.14.2`.
![image](https://user-images.githubusercontent.com/56169608/181638450-06ddca7a-e038-4631-8da7-4f44268a3e2b.png)
