### ISSUE TITLE
Question: can StyLua write to stdout instead of disk?

### ISSUE THREAD

**Issue by shmup** [JohnnyMorganz/StyLua#516]
To configure `vim` and specifically the `formatprg` for Lua, I need to have this output the rewritten content, and not just write to disk.

I notice that all the arguments for `--check` are informative outputs.

So I'd like to be able to just configure vim as such, or possibly provide an argument giving me this behavior:

```
if executable('stylua')
  setlocal formatprg=stylua
endif
```

As an example, `shfmt` https://github.com/patrickvane/shfmt does this by default, simply outputting and not writing, such that I can easily do this:

```
if executable('shfmt')
  setlocal formatprg=shfmt
endif
```

There _is_ a vim plugin for StyLua, but I tend to shy away from a plugin when the behavior can be easily configured in vanilla vim.

Cheers and thanks

**Comment by JohnnyMorganz** [comment]
Does this help? https://github.com/JohnnyMorganz/StyLua/issues/507#issuecomment-1195905718

I also want a --output=formatted on check

**Comment by shmup** [comment]
@JohnnyMorganz it does help, thank you.

Here's how I've configured my `.vim/ftplugin/lua.vim`

```vim
if executable('prettier')
  setlocal formatprg=stylua\ -
endif
```

Cheers!
