### ISSUE TITLE
Setting $XDG_CONFIG_HOME but stylua.toml still not respected

### ISSUE THREAD

**Issue by shmup** [JohnnyMorganz/StyLua#517]
Howdy! So, I have this:

`$HOME/.config/stylua/stylua.toml`

And, while I'm not used to needing to configure the `XDG_CONFIG_HOME`, I have for your README's sake:

`export XDG_CONFIG_HOME=$HOME/.config`

Am I understanding that `StyLua` will then look in `$XDG_CONFIG_HOME/stylua` for `stylua.toml` ?

If so, it's not respecting: `column_width = 80` in my tests.

Any thoughts?

**Comment by JohnnyMorganz** [comment]
Make sure you are passing `--search-parent-directories`

It is not enabled by default

https://github.com/JohnnyMorganz/StyLua#finding-the-configuration
