### ISSUE TITLE
Luau: add number separators for large numbers

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#519]
```lua
local x = 1000000
```

.. should become ...

```lua
local x = 1_000_000
```

**Comment by LastTalon** [comment]
Prettier has discussed this and decided to leave them the way the writer originally had them. The reasoning being that different people/cultures place separators in different places for different reasons. https://github.com/prettier/prettier/issues/3583#issuecomment-354159325

**Comment by JohnnyMorganz** [comment]
Aha, good point, I didn't consider this. Thank for the link.

Will probably leave this for now then, don't want to enforce placing separator location
