### ISSUE TITLE
shouldn't break on else

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#520]
0.14.2 shouldn't add a new line on the `else` on line 622
![image](https://user-images.githubusercontent.com/1550766/182649079-e48cf0c5-a9ee-409e-9bd6-3433203c7f5e.jpeg)

**Comment by JohnnyMorganz** [comment]
Looks like the thing that made it different is the introduction of a comment.

I wonder if we should be expanding the function call instead

**Comment by matthargett** [comment]
Is the original line even over the 120 character width?
