### ISSUE TITLE
Formatted tables result in unnecessary comma after last item

### ISSUE THREAD

**Issue by chreen** [JohnnyMorganz/StyLua#526]
Using VS Code extension version 1.3.2

I am unsure if this is intended or configurable, however, when formatting a script with tables, the last item is generated an unnecessary comma.

Before:
```lua
local a = {
  1,
  2,
  3,
  4,
  5
}
```

After:
```lua
local a = {
	1,
	2,
	3,
	4,
	5,
}
```

**Comment by JohnnyMorganz** [comment]
This formatting is intentional.

There are a couple of reasons why we do this:
- Reduce diff noise when you add a new element to the end of the table
- It is easier to shift elements around the table (especially with stuff like VSCode's "move line up/down" commands)
- Consistency

**Comment by chreen** [comment]
Thank you for your reply! I understand the benefits of this.
