### ISSUE TITLE
Support Lua5.4 local var attributes like <const> ? 

### ISSUE THREAD

**Issue by will** [JohnnyMorganz/StyLua#533]
https://www.lua.org/manual/5.4/manual.html#3.3.7

In 5.4 you can say things like `local color_type <const> = type(color)` but stylua can't parse the `<`

```
error: could not format file ./modules/NobleScene.lua: error parsing: error occurred while creating ast: unexpected token `<`. (starting from line 187, character 14 and ending on line 187, character 15)
additional information: expected 'end'
```

**Comment by JohnnyMorganz** [comment]
This requires 5.4 support in [full-moon](https://github.com/Kampfkarren/full-moon) which is the parser we use. It currently only supports up to 5.2

Once that is added, I'm happy to support this in stylua

**Comment by will** [comment]
Just had a chance to check this out. Works great for Playdate lua games. Thanks for this and for doing the work in full-moon!

I [posted](https://devforum.play.date/t/stylua-now-supports-lua-5-4/8648) about this at the playdate forum just to spread the word.
