### ISSUE TITLE
`if conditon then return end` suggestion

### ISSUE THREAD

**Issue by Aspekto** [JohnnyMorganz/StyLua#535]
It is very common to do
```lua
if condition then return end
-- code here
```

but stylua formats it to
```lua
if condition then 
    return
end
-- code here
```
which is a lot less appealing than the first one.

Could we have option one as the default instead?

**Comment by JohnnyMorganz** [comment]
There was extensive discussion on this issue in https://github.com/JohnnyMorganz/StyLua/issues/161, and an option was finally added in https://github.com/JohnnyMorganz/StyLua/pull/479

Setting `collapse_simple_statement` in `stylua.toml` to `ConditionalOnly` (or Always) should produce the desired effect

**Comment by Aspekto** [comment]
Where is the `stylua.toml` file located in? I am on windows.

**Comment by LastTalon** [comment]
> Also, wouldn't it be a good idea to add settings like these to the vsc extension? So that people like me who aren't aware of additions like these could easily check the extension settings.

If the settings only exist in the extension, it can cause differences in formatting between people working on the same project. The settings need to be in a file that can be shared between everyone working on the project and committed to whatever version control they're using (usually git).



> Where is the `stylua.toml` file located in? I am on windows.

It just goes in the root of your project.
