### ISSUE TITLE
Remove excess parentheses

### ISSUE THREAD

**Issue by evaera** [JohnnyMorganz/StyLua#54]
Stylua should remove excess parentheses where it is safe to do so.

```lua
local x
something((x))
```

should become:

```lua
local x
something(x)
```

However, it's not always safe to remove parentheses. Inside of binary operator expressions, parentheses can denote precedence, so these parentheses should not be removed:

```lua
local x = (1 + 2) * 3
```

Additionally, parentheses can cull extra values returned from a multiple return:

```lua
function x()
  return 1, 2
end

print(x()) --> 1, 2
print((x())) --> 1
```

In this example above, removing the parentheses in the expression `(x())` is unsafe, because it changes how the code runs.

In cases like this, Stylua should still compress down to one set: `print(((x())))` should become `print((x()))`.

**Comment by RuizuKun-Dev** [comment]
Hi @JohnnyMorganz 

Can you make this configurable?

I'd prefer to keep parenthesis for if statements

**Comment by JohnnyMorganz** [comment]
Hi @RuizuKun-Dev, I'm not 100% sure on adding a configuration, but I am happy to think about it. 

Ideally, we want as little configuration as possible, as this is an opinionated code formatter. Something like this would definitely be a heated topic between developers, with some people liking parentheses, and others not - this is what we want to avoid, we want a single, consistent style.
This is also the recommended style in the [Roblox Lua Style Guide](https://roblox.github.io/lua-style-guide/#blocks), which we follow.

**Comment by RuizuKun-Dev** [comment]
I understand, and in general I agree however I only use parenthesis to wrap if statements with a not operator.

I believe that everyone should have an option to follow the guide strictly or not and everyone should respect other people's preferences instead of forcing it upon others.
(Not saying that you or this extension is forcing anything)

With respect a small setting for parenthesis wouldn't cause an outbreak.

**Comment by JohnnyMorganz** [comment]
I know for example Prettier sometimes [*adds* parentheses](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzCFMC8mARgIYBOmAZFSaQF6YA+TOeIANCBAA4wCW0AM7JQFchADuABQoIRKUqkmkAniK7FypMAGsMAZR47+UAObIY5AK5wucALbE4AExeuAMqXPXSZuABiEOQOpDAC5sggpNYwEJwgABYwDqgA6on88ELGYHAG8ln8AG5ZqlFgQhogpkJw5DDS2mahyNhKdVwAVkIAHgBC2nqGpA5wHqZwbR12ID29BqZm6ACK1hDw06idIMbkdeRRZM6oCTzkpjBp-C4wicgAHAAMXOcQdWnaPFHncAfFUy4AEd1vAmrwFNEhABaKBwVyuBLkOAg-jIpp+VpIdrbWZ1Bz8Sw2PFLVagqbYmZcGCkYjXW73JAAJmp2n4qCWAGEIA4sSA-gBWBLWOoAFVpChxO2KtgAklB3LADGALnwAIIKgwwVToLZ1AC++qAA) when they weren't previously present - this is mainly when there are BinOps of the same precedence and to show the left associativity.

If there's places where parentheses will actually help readability, I'm happy to look into it.

**Comment by RuizuKun-Dev** [comment]
Before:
![image](https://user-images.githubusercontent.com/55673217/111242741-5788c500-8632-11eb-93a5-a072c9406c62.png)

After:
![image](https://user-images.githubusercontent.com/55673217/111242747-5a83b580-8632-11eb-8ab7-585fac82dc43.png)

Formatting breaks my if statement logic

**Comment by JohnnyMorganz** [comment]
Hm, that is odd - the parentheses shouldn't be removed here. Need to look into that
