### ISSUE TITLE
Lockfile not up to date in 0.14.3 tag

### ISSUE THREAD

**Issue by alerque** [JohnnyMorganz/StyLua#556]
The Cargo.lock file in the last tagged release 0.14.3 is not up to date with Cargo.toml. This breaks distro packaging that target reproducible builds. We can of course get it to build without using `--locked` but then the build is not reproducible (among other possible issue).

Please make sure the lockfile is refreshed before each tagged release (if not every time Cargo.toml is updated).

**Comment by JohnnyMorganz** [comment]
Yeah, I forgot to update it this release, so unfortunately had to do it in a commit aftwards. Will try to fix this

**Comment by JohnnyMorganz** [comment]
This has been fixed for 0.15.0 and future releases. I've added some checks to ensure this doesn't happen again, so I'll close this issue now.

Let me know if anything specific needs to be done for the 0.14.3 release though
