### ISSUE TITLE
Eager Wrapping with Comments

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#56]
This input gets wrapped eagerly.
```lua
last = last or #array -- If last isn't provided, go to the end
```
Becoming this, due to the comment.
```lua
last = last
	or #array -- If last isn't provided, go to the end
```
However, this remains unchanged.
```lua
last = last or #array
```

**Comment by JohnnyMorganz** [comment]
Hm, it looks like we are taking the size of the comment into account when calculating if the line is too long. We don't want to do that!

**Comment by LastTalon** [comment]
It appears the length of the comment doesn't matter.
```lua
last = last or #array --
```
becomes
```lua
last = last
	or #array --
```
as well.

**Comment by JohnnyMorganz** [comment]
Odd, but I think I know the issue - thanks for the report!

**Comment by JohnnyMorganz** [comment]
The issue here actually isn't the comment, but the `#` operator on `array`, as
```lua
foo = bar or baz -- test
```
works fine.
I did think I fixed this in https://github.com/JohnnyMorganz/StyLua/blob/master/CHANGELOG.md#040---2021-02-05, but I seemed to have missed a case, thanks for the catch!
