### ISSUE TITLE
Formatting files in hidden directories

### ISSUE THREAD

**Issue by wincent** [JohnnyMorganz/StyLua#562]
Hi @JohnnyMorganz — Thanks for building StyLua!

Wanted to ask about formatting files in hidden directories. For example, I have a bunch of Lua in [my dotfiles repo](https://github.com/wincent/wincent) under a path like `.config/nvim/`, and StyLua skips right over it. This means that instead of writing:

```sh
stylua .
```

I have to write:

```sh
stylua $PATHS_TO_HIDDEN_DIRECTORIES...
```

So, I've put this in [a script](https://github.com/wincent/wincent/blob/91ebe56f414748078c93d011f5774553bddf3537/bin/format), that does this:

```sh
stylua \
  aspects/dotfiles/files/.hammerspoon \
  aspects/nvim/files/.config
```

But this isn't "future proof" in the sense that I will have to remember to update this any time I add more files in other locations, or I move these directories.

Do you think it would be possible to allow StyLua to traverse hidden directories? Or do you have an alternative? Not sure if it would be a switch, or if it should just traverse hidden directories by default (in which case users would be able to use `.styluaignore` to avoid entering hidden directories if they didn't want them traversed).

**Comment by JohnnyMorganz** [comment]
It's definitely possible, it just hasn't been an issue yet. I think the best way is to just make it a command line flag such as `--allow-hidden`.
Just needs changing here https://github.com/JohnnyMorganz/StyLua/blob/f5243a1ff2f2a0dd59589706d7dccac03a4128f4/src/cli/main.rs#L265

**Comment by wincent** [comment]
Something like:

- https://github.com/JohnnyMorganz/StyLua/pull/563

might do the trick. Tested locally and works for me:

- Without `--allow-hidden`, `stylua .` does _not_ visit hidden hierarchies:
  - `--verbose` shows `Ignore(IgnoreMatch(Hidden))` for those entries.
- Without `--allow-hidden`, `stylua some/path/to/a/.dot-directory` still works, as before.
- With `--allow-hidden`, `stylua .` visits all the things.
