### ISSUE TITLE
Bad CPU type in executable (aarch64)

### ISSUE THREAD

**Issue by sestrella** [JohnnyMorganz/StyLua#567]
Download the latest macos-aarch64 release, however, the executable reports the wrong architecture:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/2049686/188391982-1bca7bc9-c6e1-4115-8d75-c45be1668f94.png">

**System Information**

<img width="230" alt="image" src="https://user-images.githubusercontent.com/2049686/188394777-57c242e2-8cfc-4d55-ac25-256332b4e7a3.png">

**Comment by JohnnyMorganz** [comment]
Odd, this was previously reported in https://github.com/JohnnyMorganz/StyLua/issues/528 but should've been fixed for the 0.14.3 release.

I will take a look this evening to see what's up. In the meantime, unfortunately you will have to either enable Rosetta or install manually via Cargo

**Comment by sestrella** [comment]
It looks like the GH action [runner](https://github.com/JohnnyMorganz/StyLua/blob/main/.github/workflows/release.yml#L39-L41) used to produce this binary is based on x86_64:


<img width="426" alt="image" src="https://user-images.githubusercontent.com/2049686/188488235-a3780867-de5a-4f8f-bef9-3fc4691b5835.png">

Source: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

After doing some research, it looks like support for [Apple M1 silicon options](https://github.com/github/roadmap/issues/528) is only available for hosted runners

**Comment by JohnnyMorganz** [comment]
#569 should hopefully fix this, but this will only be test-able in the next release. I'd be interested to know if it works

**Comment by sestrella** [comment]
I'll give it a try, thank you @JohnnyMorganz!

**Comment by JohnnyMorganz** [comment]
@sestrella I was able to trigger a build early to see if this works. You can find the artifact in https://github.com/JohnnyMorganz/StyLua/actions/runs/2996073879, do you mind checking if this is correct?

**Comment by sestrella** [comment]
@JohnnyMorganz the CI output looks clean, however, in order to test it locally, I would have to download the asset, unfortunately, I don't think I have enough rights for that unless there is a public release

**Comment by JohnnyMorganz** [comment]
Ah, that is a shame. There should've been artifacts available on the bottom of that page, but maybe they aren't downloadable. No worries, we can wait to release - it looks like it worked correctly though when I downloaded locally and ran `file` on the binary

**Comment by sestrella** [comment]
@JohnnyMorganz my bad! I was looking at the wrong place:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/2049686/188556871-d6908c34-0962-45e2-8173-42e771057ffa.png">

I downloaded the artifact directly from the GH action run, and the binary seems to work fine now 🚀, thank you very much!

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2049686/188557897-19cb0d11-ebe8-4526-ae9c-73da89879a44.png">

PS, the only weird thing is that the `stylua-macos-aarch64` artifact contains another zip inside? But maybe that is because I'm downloading the artifact directly from the GH action run.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/2049686/188557951-76222f35-626f-48bb-88f1-b75dddcd6f02.png">
