### ISSUE TITLE
Lines wrap incorrectly inside function call with trailing comments

### ISSUE THREAD

**Issue by KyleMit** [JohnnyMorganz/StyLua#57]
## Input

```lua
function sayHello(
	name,    -- YourName
	greeting -- Message
)
	return greeting .. ", " .. name
end
```

## Output

```lua
function sayHello(name, greeting -- Message)
	return greeting .. ", " .. name
end
```

Expected output should stay the same as input. This is perhaps related to the existing issue to allow for wrapping within a functional call (#34), but more problematic in that it creates a syntax error when wrapping params with trailing comments

## Related Issues

* #34 - Hang expressions within a function call if necessary
* #11 - Comments wrap incorrectly at the beginning of tables
* #23 - Moving code onto one line with comment breaks code

**Comment by JohnnyMorganz** [comment]
It also looks like it is losing comments within the function arguments too
