### ISSUE TITLE
Improve formatting for hanging binary operators

### ISSUE THREAD

**Issue by sayhisam1** [JohnnyMorganz/StyLua#58]
Stylua should try to keep math operations of the form  '(a [+ or -] b) [* or /] c'  on the same line whenever possible.

For example, Stylua should group the following:
```
local ratio = (minAxis - minAxisSize)
        / delta
        * (self.props.maxScaleRatio - self.props.minScaleRatio)
        + self.props.minScaleRatio
```

as:
```
local ratio = (minAxis - minAxisSize) / delta
        * (self.props.maxScaleRatio - self.props.minScaleRatio)
        + self.props.minScaleRatio
```

this is a good idea because it makes it easier to reason about formulas in terms of addition/subtraction over many smaller terms.

**Comment by JohnnyMorganz** [comment]
Thank you for the suggestion! This was also brought up by someone else outside of GitHub.

This is definitely something I want to do, but currently full-moon https://github.com/Kampfkarren/full-moon/issues/64 (the parser we use, and hence StyLua) has no knowledge of precedence rules for operators, which makes this difficult. Ideally, we would group together all the expressions with the same precedence, then break the outermost group onto multiple lines, and keep going in as necessary.

We could try and hack together some sort of precedence inside of StyLua and see how we go, or I will try and get a PR going in full-moon
