### ISSUE TITLE
Parsing error with double inline comments

### ISSUE THREAD

**Issue by Stanzilla** [JohnnyMorganz/StyLua#585]
I have this line that StyLua chokes on with `error: could not format file ./WeakAuras/Types.lua: error parsing: error occurred while tokenizing: unclosed comment at line 1689, column 5`

`    --["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-45"] = "Targeting Eye", -- Duplicate of 53` [full file](https://github.com/WeakAuras/WeakAuras2/blob/stylua/WeakAuras/Types.lua)

**Comment by JohnnyMorganz** [comment]
Is this with the latest version? Did it work with 0.14.3? Latest version upgrades the parser which uses a new tokenizer and might have a bug

**Comment by Stanzilla** [comment]
I assume it worked with 14.3 since it did not error before and I just upgraded to 15, yeah!

**Comment by matthargett** [comment]
A few other examples that fail to parse in 0.15, but were fine in 0.14.3:
```
function stringify(value: any): string
        if _G.__DEV__ then
                return ([=[[%s]]=]):format(Array.join(
                ))
        end
        return ([[{%s}]]):format(Array.join(
                Array.map(entries, function(entry)
                        return ([["%s":%s]]):format(entry[1], entry[2])
                end),
                ","
        ))
end
```

```
--[Common IPAs]--
```

and

```
--( xyz doesn't abc )
```

**Comment by Kampfkarren** [comment]
Should be moved to full-moon repo

**Comment by matthargett** [comment]
> Should be moved to full-moon repo

https://github.com/Kampfkarren/full-moon/issues/241

**Comment by clason** [comment]
Here's another (second line is the one that triggers the warning about the backtick character):
```lua
  --`signatures` the value defaults to zero or is ignored if `signatures.length
  --=== 0`. Whenever possible implementors should make an active decision about
```

**Comment by JohnnyMorganz** [comment]
Looks like there are still some problems with full-moon.
Current recommendation is to temporarily downgrade to 0.14.3. Will try to get this fixed once im free
