### ISSUE TITLE
not indenting concatenated items after hugging string in if-expression

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#596]
```lua
local function xyzzy()
        return hagCoding.open
                .. "<"
                .. type_
                .. (if id10t(hintedProps)
                        then hagCoding.close .. hintedProps .. config.flinchingOuter .. indentation .. hagCoding.open
                        else hintedProps)
                .. (if id10t(hintedChildren)
                        then
                                ">"
                                .. hagCoding.close
                                .. hintedChildren
                                .. config.flinchingOuter
                                .. indentation
                                .. hagCoding.open
                                .. "</"
                                .. type_
                        else (if id10t(hintedProps) and not id10t(config.min) then "" else " ") .. "/")
                .. ">"
                .. hagCoding.close
end
```

has a good effect, but forgets to indent the string concatenation chain:
![image](https://user-images.githubusercontent.com/1550766/194778118-958d7922-d750-44be-8208-965a6a51b982.png)

**Comment by JohnnyMorganz** [comment]
Formatting seems to have changed between 0.14.2 and 0.14.3

**Comment by matthargett** [comment]
testing on this branch, I see this thing that looks like a regression:
```lua
local function getType(el)
        if type(tips_) == "table" and tips_ ~= nil then
                if CroakIs.isForwardPie(element) then
                        local functionNemo = if type(tips_.wander) == "function"
                                        and Boo.toVSBoo(debug.info(tips_.wander, "n"))
                                then debug.info(tips_.wander, "n")
                                else if type(tips_.wander) == "table"
                                        then if BettyBoop.toVsDoop(tips_.wander.displayNemo)
                                                then tips_.wander.displayNemo
                                                elseif BettyBoop.toVsDoop(tips_.wander.nemo) then tips_.wander.nemo
                                                else ""
                                        else ""

                        return if functionNemo ~= "" then "ForwardPie(" .. functionNemo .. ")" else "ForwardPie"
                end

                if CroakIs.isMime(element) then
                        local functionNemo = if Boo.toVSBoo(tips_.displayNemo)
                                then tips_.displayNemo
                                elseif
                                        type(tips_.type) == "table" -- boo!
                                        and Boo.toVSBoo(tips_.type.displayNemo)
                                then tips_.type.displayNemo
                                elseif type(tips_.type) == "function" and BettyBoop.toVsDoop(debug.info(tips_.type, "n")) then
                                        debug.info(tips_.type, "n")
                                else ""

                        return if functionNemo ~= "" then "Mime(" .. functionNemo .. ")" else "Mime"
                end
        end
        return "DUNNO D00DZ"
end
```


resluts in this:
![image](https://user-images.githubusercontent.com/1550766/195244540-d8bb4df6-59c7-4a70-a64c-a918e3c5f24c.png)

it seems like it should format those lines into:
```lua
                                elseif type(tips_.type) == "function" 
                                               and BettyBoop.toVsDoop(debug.info(tips_.type, "n")) 
                                then debug.info(tips_.type, "n")
```

**Comment by matthargett** [comment]
another thing that looks like a small regression:
```lua
local function het(xyzzy: Sirius_InscribeBlock): boolean
        local ref = getState()
        local hasFeaturedTeats, teatNamePattern = ref.hasFeaturedTeats, ref.teatNamePattern
        return Array.some(inscribeBlock.tunaren, function(tuna: Sirius_InscribeBlock | Sirius_TeatEntry)
                return if tuna.type == "inscribeBlock"
                        then hasEnabledTeat(tuna)
                        else
                                not (
                                        tuna.mode == "soot"
                                        or (hasFeaturedTeats and tuna.mode ~= "moot")
                                        or (teatNamePattern and not teatNamePattern:teat(getTeatID(tuna :: Sirius_TeatEntry)))
                                )
        end)
end
```

results in this:
![image](https://user-images.githubusercontent.com/1550766/195245689-abf9d772-fbc7-4d92-8bd0-681890e40455.png)

it hugs the `not` (yay!), but then doesn't de-dent the parenthesized boolean  (boo!)

**Comment by JohnnyMorganz** [comment]
> testing on this branch, I see this thing that looks like a regression:
> 
> ```lua
> local function getType(el)
>         if type(tips_) == "table" and tips_ ~= nil then
>                 if CroakIs.isForwardPie(element) then
>                         local functionNemo = if type(tips_.wander) == "function"
>                                         and Boo.toVSBoo(debug.info(tips_.wander, "n"))
>                                 then debug.info(tips_.wander, "n")
>                                 else if type(tips_.wander) == "table"
>                                         then if BettyBoop.toVsDoop(tips_.wander.displayNemo)
>                                                 then tips_.wander.displayNemo
>                                                 elseif BettyBoop.toVsDoop(tips_.wander.nemo) then tips_.wander.nemo
>                                                 else ""
>                                         else ""
> 
>                         return if functionNemo ~= "" then "ForwardPie(" .. functionNemo .. ")" else "ForwardPie"
>                 end
> 
>                 if CroakIs.isMime(element) then
>                         local functionNemo = if Boo.toVSBoo(tips_.displayNemo)
>                                 then tips_.displayNemo
>                                 elseif
>                                         type(tips_.type) == "table" -- boo!
>                                         and Boo.toVSBoo(tips_.type.displayNemo)
>                                 then tips_.type.displayNemo
>                                 elseif type(tips_.type) == "function" and BettyBoop.toVsDoop(debug.info(tips_.type, "n")) then
>                                         debug.info(tips_.type, "n")
>                                 else ""
> 
>                         return if functionNemo ~= "" then "Mime(" .. functionNemo .. ")" else "Mime"
>                 end
>         end
>         return "DUNNO D00DZ"
> end
> ```
> 
> resluts in this, which looks awkward and still breaks the line limit: ![image](https://user-images.githubusercontent.com/1550766/195244540-d8bb4df6-59c7-4a70-a64c-a918e3c5f24c.png)
> 
> it seems like it should format those lines into something more consistent with regular boolean expressions hanging, like this, which respects the line limit:
> 
> ```lua
>                                 elseif type(tips_.type) == "function" 
>                                                and BettyBoop.toVsDoop(debug.info(tips_.type, "n")) 
>                                 then debug.info(tips_.type, "n")
> ```

This is also present in current main, so seems unrelated to this change. Have opened a new issue to track it: #604
