### ISSUE TITLE
Support inline comments to ignore formatting in parts of source file

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#60]
We should support ignoring parts of a file inline within the code. This can be done by using a comment, such as `-- stylua: ignore`.

This can especially useful if StyLua is currently formatting something incorrectly, which will be fixed in a later update. For the time being, a user can quickly ignore the next node within the source file using the comment, allowing them to continue using StyLua and coding without hassle. This can very much help with adoption in the early stages, where StyLua output isn't completely optimal.
It is also very useful for cases where StyLua causes a syntax error due to its formatting (see #57 #41 or #26 for a few examples). We want to fix these issues, but this should help in not being a pain for the end user.

Other cases may be where code is structured in a specific format, and the user wants to keep it that way.
For example:
```lua
local matrix = {
    { 0, 0, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 },
}
```
Keeping this in its current form is much better for readability compared to expanding everything onto multiple lines.
Ideally, we would want this type of use case to happen as little as possible, however StyLua can't cover everything. This can also help in adoption of StyLua in some codebases.

Before formatting expressions within StyLua, we should read the leading trivia to see if the ignore comment is present. If so, we can skip the current node for formatting. One thing we must consider is at what level these comments should be allowed: statement level, or a more granular node level? We also need to ensure that if a specific part of the code is ignored, it doesn't affect the rest of the code by e.g., causing a syntax error since it wasn't formatted.

**Comment by LastTalon** [comment]
This could also be expanded to support ignore ranges like prettier.

How prettier handles it for reference: https://prettier.io/docs/en/ignore.html

I think it would also be nice to possibly support a LuaDoc style annotation for ignoring in addition to the normal comment. Something like `-- @stylua ignore` possibly?

**Comment by JohnnyMorganz** [comment]
I'm not entirely sure what you mean by the LuaDoc style annotation - will this have any difference in function compared to the normal comment, or is just for stylistic purposes? I would rather just keep a single, standard comment if that's the case.
