### ISSUE TITLE
unexpected character ~

### ISSUE THREAD

**Issue by snowman** [JohnnyMorganz/StyLua#603]
```sh
$ cat /tmp/a.lua
n = 2 ~ 4
print(n)
```

```sh
$ stylua /tmp/a.lua
error: could not format file /tmp/a.lua: error parsing: error occurred while tokenizing: unexpected character ~ at line 1, column 7
```

```sh
$ lua /tmp/a.lua
6
```

**Comment by JohnnyMorganz** [comment]
How did you build/install StyLua?

If it's through cargo, make sure to pass `--features lua53`
```
cargo install --features lua53 stylua
```

If it's through GitHub Releases, this shouldn't be happening. If it's another source, will have to look at how they build the binary

**Comment by snowman** [comment]
Thanks, I install `stylua` with `cargo`

```sh
$ cargo install --features lua53 stylua
```

solves the problem
