### ISSUE TITLE
Syntax error when formatting luau return type and trailing comment

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/StyLua#608]
Formatting a function with a comment after a single return type enclosed in parentheses formats the code from something like this:

```lua
function foo(): (
	nil -- Some comment
)
	return nil
end
```

To this:

```lua
function foo(): (nil -- Some comment)
	return nil
end
```

The closing parentheses is now part of the comment and produces a syntax error.
StyLua could either enforce no parentheses on single return types or format it as the original code block when parentheses are found, either solution works IMO.

**Comment by JohnnyMorganz** [comment]
Going to separate out the parentheses removal as a separate feature request
