### ISSUE TITLE
Precedence of certain operations is tampered by formatting.

### ISSUE THREAD

**Issue by bmcq-0** [JohnnyMorganz/StyLua#623]
The formatter currently removes necessary parentheses around certain expressions. Take the following code for example:

```lua
return (-X) ^ Y
```

...is formatted to:

```lua
return -X ^ Y
```

These expressions are NOT the same and this will lead to very obscure issues (``-X ^ Y`` being parsed as ``-(X ^ Y)`` and not ``(-X) ^ Y`` seems to be not commonly known and will cause issues especially for beginners.

**Comment by JohnnyMorganz** [comment]
Definitely a major bug, thanks for the report. Will look to fix this.
