### ISSUE TITLE
Inconsistent indentation for anonymous function assignments with comments.

### ISSUE THREAD

**Issue by bmcq-0** [JohnnyMorganz/StyLua#627]
See the following code:

```lua
t = t or function()
	print("Hello, World") -- comment
end

t = t or function()
	print("Hello, World")
end
```

These are the exact same. However, the first has a comment in one of the statements. When formatting, this seems to somehow cause indentation inconsistencies:

```lua
t = t or function()
		print("Hello, World") -- comment
	end

t = t or function()
	print("Hello, World")
end
```

The comment can be anywhere, but the assinment seems to have to be in the form of a binary operation (?) (``t = function()...`` does not yield the same inconsistencies, only ``t = t or ...``)

**Comment by JohnnyMorganz** [comment]
I think this should get fixed when #591 is merged
