### ISSUE TITLE
Incorrect range formatting of files containing Unicode characters

### ISSUE THREAD

**Issue by Mullets-Gavin** [JohnnyMorganz/StyLua#63]
I am getting extremely strange file formatting with StyLua, and it's causing errors to pop up. I have no steps to reproduce this, but you can reproduce it via this file (copy the raw and paste into your editor):
https://github.com/Mullets-Gavin/Loader/blob/aaacee809466c1225f5bad8609b56a4f513faeff/src/Manager.lua

I'm not sure where it goes wrong, but it consistently moves the bottom lines of this file around and keeps causing errors.

Broken:
![image](https://user-images.githubusercontent.com/38087728/109160334-a6ce8a80-7743-11eb-9fa3-668672e1a046.png)

Normal:
![image](https://user-images.githubusercontent.com/38087728/109160487-dc737380-7743-11eb-9633-c5b923dab622.png)

**This is just a snapshot. there are other files doing the exact same thing, and causing me to have errors which then forces me to fight the formatter.**

**Comment by JohnnyMorganz** [comment]
The source file contains unicode character. This means VSCode is sending over incorrect range start/end positions (as it sends character, not byte offsets), causing the range to be misaligned. In combination with this, then the range formatting seems to be something wonky, breaking the formatting in places where it shouldn't

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/StyLua/commit/c0e9fc1f92b539c4a3c45c7734db633223e0141b provides a fix in the extension to make it use byte offsets from character offsets.

There are still two things we need to consider:

- Should we do the conversion from character to byte offsets within the StyLua binary instead? Is it more performant?
- Why did the incorrect range lead to such a wild output? Need to debug using the range provided ourselves and see whats causing the errors to occur - that shouldn't have happened regardless if it was a range issue. This may also be affecting when people use `Format Selection` itself.
