### ISSUE TITLE
add support wow api (1.12)

### ISSUE THREAD

**Issue by shikulja** [JohnnyMorganz/StyLua#630]
including (blocked api)
StyLua, does a good job, but I think the formatting could be better if the program detects the wow api better

**Comment by JohnnyMorganz** [comment]
Not fully sure what you mean by this.

We try not to look for specific API calls and format them a particular way, it should be as general as possible.

If you have specific examples of some API calls which are badly formatted, I'm happy to take a look at those and see what we can improve generally

**Comment by shikulja** [comment]
> We try not to look for specific API calls and format them a particular way, it should be as general as possible.

Okay, I thought it worked like syntax highlighting with formatting only, with function and type definitions.

I would like to have an option that allows you to change "tabbing" only at the beginning and end of lines, but not in the middle of the code (value alignment). But I can do without it.

Thank you for the clarification
