### ISSUE TITLE
New String Interpolation feature breaks StyLua

### ISSUE THREAD

**Issue by medallyon** [JohnnyMorganz/StyLua#638]
The latest feature for Studio is JavaScript/C# style string interpolation: https://devforum.roblox.com/t/string-interpolation-available-for-studio/2127058

Attempting to format a file that contains backticks (<kbd>`</kbd>) breaks StyLua with the following error message:

```
Could not format file: error: failed to format from stdin: error parsing: error occurred while tokenizing: unexpected character ` at line 58, column 41
```

**Comment by JohnnyMorganz** [comment]
Support for this was added in #635 and should be available in the next release
