### ISSUE TITLE
Empty table with comment wrongly collapses closing parenthesis into comment

### ISSUE THREAD

**Issue by sircfenner** [JohnnyMorganz/StyLua#64]
Input:
```Lua
local foo = { -- test
}
```
Output:
```Lua
local foo = { -- test}
```
Expected output: input is unchanged.

Observed on VSCode extension version 1.1.1.
<hr>

This behavior can also result from more common syntax:
```Lua
local foo = {
    -- test
}
```
*run StyLua*
```Lua
local foo = { -- test
}
```
*run StyLua*
```Lua
local foo = { -- test}
```

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/StyLua/commit/9eda01cb5bd0083fbbd87708705d85ec2cbfbba3 should fix the main issue here, and the table will no longer collapse.
However, with the second example you gave, currently the comment gets incorrectly indented. I am waiting to see if  https://github.com/Kampfkarren/full-moon/pull/125 gets merged as this will affect the fix
