### ISSUE TITLE
StyLua reports AST difference when formatting useless parentheses in Luau types

### ISSUE THREAD

**Issue by Kampfkarren** [JohnnyMorganz/StyLua#643]
Given `type x = (number)`, `stylua --verify sample.lua` gives the "output AST may be different to input AST" error. Formatting produces `type x = number`.

**Comment by JohnnyMorganz** [comment]
Fix released in v0.16.1 https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.16.1
