### ISSUE TITLE
Using sort_requires in config file causes unknown field error

### ISSUE THREAD

**Issue by 2KAbhishek** [JohnnyMorganz/StyLua#654]
System: Mac Mini M2
Stylua: 0.16.1 (homebrew)

Adding the config for `sort_requires` (directly from the README) complains with this error:

```bash
❯ stylua lua/nvim2k/plugins/null-ls.lua
error: Config file not in correct format: unknown field `sort_requires`, expected one of `column_width`, `line_endings`, `indent_type`, `indent_width`, `quote_style`, `no_call_parentheses`, `call_parentheses`, `collapse_simple_statement` at line 7 column 1
```

**Comment by JohnnyMorganz** [comment]
Sorry, this isn't actually released yet. I've been meaning to get a new release out soon but got caught up with work.

You can build from source manually if you want the feature now, otherwise I'll hopefully cut a release on the weekend.

**Comment by 2KAbhishek** [comment]
Thanks for the response and thank you for the tool, looking forward to the release!

I had raised the issue in case you were unaware :)
Will close this after the release

**Comment by JohnnyMorganz** [comment]
v0.17.0 has finally been released, sorry for the long delay!
https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.17.0

**Comment by 2KAbhishek** [comment]
Thanks for the update @JohnnyMorganz!
