### ISSUE TITLE
Extension fails to check version when providing an aftman binary path

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#657]
When attempting to provide an path to an aftman binary I get this error. It appears that the extension is attempting to execute the binary for the version check from outside the project.

```
Error checking the selected StyLua version, falling back to the currently installed version: Error: Command failed: "/home/lucas/.aftman/bin/stylua" --version Aftman error: Tried to run an Aftman-managed version of stylua, but no aftman.toml files list this tool. To run stylua from this directory, add it to one of these files: - /home/lucas/.aftman/aftman.toml
```

Strangely, this doesn't seem to prevent the extension from formatting files. It simply complains that it can't check the version.

**Comment by JohnnyMorganz** [comment]
We probably don't specify the cwd when performing the version check
