### ISSUE TITLE
Option to disable call_parentheses

### ISSUE THREAD

**Issue by autonordev** [JohnnyMorganz/StyLua#668]
Similar to #242.

I propose to add a 'disable' option to call_parentheses (possibly named `Disable`, `Ignore`, `Auto`, or `Detect`). This means that StyLua will leave parentheses alone, and follow whatever is already within the code.

The primary advantage of this proposal is that it allows for parenthesis guidelines which are more complicated than StyLua's current options without necessitating further customisation.

This option would effectively act as an 'escape hatch' (see Drawback No.2) and would create a responsibility on the maintainers and contributors of user projects - should they wish to prevent parenthesis anarchy - to set and enforce rules. Thus, use of this option would be at the risk of the user; if this proposal is implemented, it may be wise to communicate this risk in the README.

## Drawbacks

**1. Opinionation**

While more configuration makes StyLua a less opinionated tool, this option could act as a reasonable compromise between those who want more configuration for parentheses and those who do not.

**2. Automation**

StyLua's advantages of automation and minimising nitpicking would not apply to parentheses within a project using this option.

However, the alternative is either:

- to determine, for each use case (of which there is a theoretically infinite number), the value of adding a new option *and* then implementing such; or
- simply not adding any further options, which (as described below) can be harmful to projects

Parentheses are a unique and divisive issue, thus - in my view - the most practical solution is to provide an off switch for those who understand the implications and believe it is in the best interests for their project.

## Background

Like all sane developers (😉), I have call_parentheses set to `Always`. However, there are certain cases, primarily when using specific third-party libraries, where parentheses can make code more noisy and unclear.

Using the amazing and popular Fusion library - which uses the absence of parentheses as a style *most of the time* - as an example, here is an example component:

```lua
New "Frame" {
	[Children] = {
		TopLabel {},

		New "ScrollingFrame" {
			[Children] = {
				New "UIListLayout" {
					[OnChange "AbsoluteContentSize"] = function(value)
						-- ...
					end,
				},
			},
		},
	},

	[Cleanup] = {
		joinConn,
		leaveConn,
		teamConn,
	},
}
```

However, formatting this with StyLua brings this result:

```lua
New("Frame")({
	[Children] = {
		TopLabel({}),

		New("ScrollingFrame")({
			[Children] = {
				New("UIListLayout")({
					[OnChange("AbsoluteContentSize")] = function(value)
						-- ...
					end,
				}),
			},
		}),
	},

	[Cleanup] = {
		joinConn,
		leaveConn,
		teamConn,
	},
})
```

Especially with a smaller tab size (i.e. 2 columns, far lower than GitHub's default of 8), these parentheses can be problematic and harm readability.

### Using another styling option

I do not want to omit parentheses in my code, except for when interacting with the Fusion library, even when calling with a single string or a single table.

Similarly, setting different configurations per directories would be undesirable; StyLua does not support this and adding it would significantly increase the technical complexity of the tool, but I also wish to use parentheses for my non-Fusion code within components. [Elttob's comment on issue 242 goes further in depth on this point.](https://github.com/JohnnyMorganz/StyLua/issues/242#issuecomment-921582295)

### Ignoring

Currently, we workaround this by `.styluaignore`ing our Fusion component directories. However, this means that our component code does not benefit from StyLua's formatting, which leads to:

- a (usually significant) amount of code that is deviant to style rules
- excessive nits in code review
- developers having to think about minute style rules, such as trailing commas

which all suck, and are the reasons why StyLua exists at all. Leading to the proposal within this issue.

**Comment by JohnnyMorganz** [comment]
Thanks for opening this issue!
I agree, its very difficult to find a one-size-fits-all solution to the parentheses problem.
The loss of automation in the drawbacks is significant imo, which is why I have been previously hesitant about adding an escape hatch like this. Of course, if a developer explicitly subscribes to it, then they have made a decision to accept that.

I'll leave it up for discussion to see what other people think.

**Comment by Zodanim** [comment]
I've personally run in to this issue today when working with Fusion, because as this issue brings up and as [Elttob mentioned in the comment @autonordev brought up](https://github.com/JohnnyMorganz/StyLua/issues/242#issuecomment-921582295), not having a "leave as is" option forces me to either have code that looks like this:
```lua
local Fusion = require(ReplicatedStorage:WaitForChild("Packages"):WaitForChild "Fusion")
-- this isn't the *worst* but it just doesn't make sense to omit the parentheses here
```
Or code that looks like this:
```lua
[Children] = {
	New("UICorner")({
		CornerRadius = frameRadius,
	}),
	New("UIPadding")({
		PaddingLeft = framePadding,
		PaddingRight = framePadding,
		PaddingBottom = framePadding,
		PaddingTop = framePadding,
	}),
	New("UIListLayout")({
		FillDirection = Enum.FillDirection.Horizontal,
		HorizontalAlignment = Enum.HorizontalAlignment.Left,
		Padding = UDim.new(0, 15),
		SortOrder = Enum.SortOrder.LayoutOrder,
		VerticalAlignment = Enum.VerticalAlignment.Center,
	}),
	New("ImageLabel")({
		BackgroundTransparency = 1,
		Image = props.statIcon,
		ImageColor3 = props.statColor,
		ImageTransparency = 0.5,
		LayoutOrder = 1,
		Size = UDim2.fromScale(1, 1),
		[Children] = New("UIAspectRatioConstraint")({
			AspectRatio = 1,
		}),
	}),
	New("TextLabel")({
		AnchorPoint = Vector2.new(0, 0.5),
		AutomaticSize = Enum.AutomaticSize.X,
		BackgroundTransparency = 1,
		Font = Enum.Font.Gotham,
		LayoutOrder = 2,
		Size = UDim2.fromScale(0, 0.8),
		Text = tostring(props.statValue),
		TextColor3 = props.statColor,
		TextScaled = true,
		TextStrokeTransparency = 1,
		TextTransparency = 0.5,
		TextXAlignment = Enum.TextXAlignment.Right,
	}),
},
```
I want the parentheses to be omitted on the latter code example but I don't want that on the former one, this isn't possible right now so I'm all for this suggestion, I'd love an option that disables styling parentheses.

As you mentioned @JohnnyMorganz:

> Of course, if a developer explicitly subscribes to it, then they have made a decision to accept that.

If it's opt-in it's, in my opinion, on the developer and not StyLua.

**Comment by JohnnyMorganz** [comment]
Ok, I think I will concede and add this in. I want to make the tool useful for you all in this scenario, so it seems like this is a reasonable compromise, plus we already have a setting for part of this already.
