### ISSUE TITLE
Strange formatting at pasting code

### ISSUE THREAD

**Issue by freMea** [JohnnyMorganz/StyLua#67]
VS Code version | OS | Extension version
------------------ | ---- | ----
1.53.2  | Win 10 x64 pro (french) 18363. | 1.1.1

## Steps to reproduce

When pasting, it deletes the line above and if there were no empty line, it concatenates with the line above. Well this animated screenshot will show it. Read the code comments on the screenshot.

![Gif Animate 2021-03-03 16h45 #96 _optimized](https://user-images.githubusercontent.com/22337329/109831894-25459380-7c40-11eb-8e01-302f509f7905.gif)

It is more or less fixed after a format command but remains annoying.

**Comment by JohnnyMorganz** [comment]
I'm assuming you have `Format on Paste` enabled here. This seems to be an issue similar to #63, in that range formatting seems to be doing something odd with the code which is outside of the range.

I think I know the way to solve this, but this is dependant on whether https://github.com/Kampfkarren/full-moon/pull/125 is merged or not

**Comment by freMea** [comment]
> I'm assuming you have `Format on Paste` enabled here. This seems to be an issue similar to #63, in that range formatting seems to be doing something odd with the code which is outside of the range.
> 
> I think I know the way to solve this, but this is dependant on whether [Kampfkarren/full-moon#125](https://github.com/Kampfkarren/full-moon/pull/125) is merged or not

True. For now, I disabled format on save for LUA files.
