### ISSUE TITLE
How does StyLua relate to LuaRock's "Lua Style Guide" and other Lua style guides?

### ISSUE THREAD

**Issue by gbroques** [JohnnyMorganz/StyLua#693]
What is the relationship between this project and [LuaRock's "Lua Style Guide"](https://github.com/luarocks/lua-style-guide) — and the other Lua style guides linked to from that style guide?

I'm new to Lua, and recently began writing it through Neovim configuration.

This style guide is one of the main ones that come up when you google "lua style guide".

Additionally, the [LuaLS/lua-language-server](https://github.com/LuaLS/lua-language-server/wiki/Formatter#formatter) uses [CppCXY/EmmyLuaCodeStyle](https://github.com/CppCXY/EmmyLuaCodeStyle) as its style guide for formatting.

**Comment by JohnnyMorganz** [comment]
StyLua is largely based off the Roblox Lua Style Guide: https://roblox.github.io/lua-style-guide/

**Comment by gbroques** [comment]
> StyLua is largely based off the Roblox Lua Style Guide: https://roblox.github.io/lua-style-guide/

Thank you @JohnnyMorganz!

Is it worth mentioning this in the README somehow?

I found it hard to know what style of code StyLua would enforce without a link to this guide.

**Comment by JohnnyMorganz** [comment]
Yeah, probably worth adding it somewhere if I don't forget

**Comment by gbroques** [comment]
> Yeah, probably worth adding it somewhere if I don't forget

Ok, I'll leave this open as a reminder for now then.

Thank you again!
