### ISSUE TITLE
The collapse_simple_statement option doesn't respect column_width

### ISSUE THREAD

**Issue by dtcyganok** [JohnnyMorganz/StyLua#704]
If `collapse_simple_statement = 'Always'` code blocks collapse even when their final length bigger than `column_width`

**Comment by JohnnyMorganz** [comment]
I'm not completely sure what you mean.
Can you provide a code example?

**Comment by dtcyganok** [comment]
I have this in my `.stylua.toml`:
```toml
column_width = 100
collapse_simple_statement = 'Always'
```
And after auto formatting i have code:
```lua
vim.api.nvim_create_user_command('F', function(options) require('grep').by_fixed(options.args) end, {
  nargs = '+',
  complete = 'file',
})
```
The length of the first line of lua code is bigger than 100
