### ISSUE TITLE
File contents deleted completely

### ISSUE THREAD

**Issue by jonashaag** [JohnnyMorganz/StyLua#708]
Sometimes when I run Stylua some of the files are wiped completely. ~~I think this only happens when there is an error in any of the files~~ Update: This is actually not the case. Random files are wiped.

The command I use:

```
stylua ~/.config/nvim/**/*lua
```

Interestingly, the broken file is not wiped, but some of the good ones are wiped. Wiped = all contents are removed, but the file is not deleted.

**Comment by JohnnyMorganz** [comment]
That is very odd (and concerning)

If you run it with `--verbose` it will let you know which files it formats - out of the files it lists as formatted, are all of them wiped?

Also, do you have a minimal example to reproduce this?

**Comment by JohnnyMorganz** [comment]
Oh, also - stylua doesn't do glob expansion for the paths you provide (instead there is a --glob flag), I assume that's your shell. If you run just `stylua ~/.config/nvim` does this issue still happen?

**Comment by jonashaag** [comment]
I was able to reproduce it just now, will try to reduce to a minimal example

```
/tmp ❯ cp -r ~/.config/nvim nvim
/tmp ❯ stylua nvim/**/*lua
/tmp ❯ wc -l nvim/lua/plugins/*lua
       8 nvim/lua/plugins/auto-hlsearch.lua
       ...
       0 nvim/lua/plugins/theme.lua
       ...
     158 total
/tmp ❯ wc -l ~/.config/nvim/lua/plugins/*lua
       8 /Users/j/.config/nvim/lua/plugins/auto-hlsearch.lua
       ...
      23 /Users/j/.config/nvim/lua/plugins/theme.lua
      ...
     181 total
```

**Comment by jonashaag** [comment]
OK here is a reproducer. Sorry that it's not minimal.

The problem only appears if you pass `nvim/lua` (the folder) and more arguments (either `nvim/*/*/*lua` as below, or another `nvim/lua`).

```
for i in `seq 20`; do rm -rf nvim && tar xf nvim.tar && stylua nvim/lua nvim/*/*/*lua && wc -l nvim/lua/plugins/*lua | grep 0; done
```

There should be no lines with `wc == 0`.

[nvim.zip](https://github.com/JohnnyMorganz/StyLua/files/11715429/nvim.zip)

**Comment by jonashaag** [comment]
Wild guess: all files are styled concurrently and there is a race condition when writing the same file twice. Files are written twice because the containing folder is given as an argument as well as the individual files.

**Comment by JohnnyMorganz** [comment]
Yep, I think you are right in that the issue lies when we attempt to format the same file twice. A simple uniqueness check with a set should work. Thanks for the report!
