### ISSUE TITLE
New release breaks Github action

### ISSUE THREAD

**Issue by Zottelchen** [JohnnyMorganz/StyLua#717]
Hi,

v18.0 breaks the Github action `stylua-action`, probably because there is a release.zip inside of the releases (e.g. `stylua-linux.zip` -> `release.zip` -> `stylua`).

Thank you for your work on this :)

**Comment by JohnnyMorganz** [comment]
Agh, very sorry. I had to build them separately because the release action didn't work. Let me fix this

**Comment by JohnnyMorganz** [comment]
It should be fixed now, please try again.
Sorry for inconvenience!

**Comment by Zottelchen** [comment]
Yes, it works again :) Thank you so much 👍
