### ISSUE TITLE
Luau String Interpolation can't be parsed (aka creating strings with a `backtick` )

### ISSUE THREAD

**Issue by nightcycle** [JohnnyMorganz/StyLua#718]
Everytime I run stylua from the command line, any script that constructs strings like [described here in the Luau website](https://luau-lang.org/syntax#string-interpolation) will error. Here's an example of the output:
```sh
error: could not format file src\Client\Tool\Weapon\Ranged\init.luau: error parsing: error occurred while tokenizing: unexpected character ` at line 54, column 8
```
here's the line being referenced:
```luau
error(`No muzzle found for {tool:GetFullName()}`)
```

Would be great to get this patched! I've been using these backticks more and more recently for error statements and assertions, so this will probably only get worse long term in my own workflow.

Thank you!

**Comment by JohnnyMorganz** [comment]
What version are you on and how do you build StyLua? This should already be supported

**Comment by nightcycle** [comment]
That explains it - looks like I'm having an issue with foreman not actually swapping stuff. 
![image](https://github.com/JohnnyMorganz/StyLua/assets/77173389/d63c73a6-4a4e-4727-b51d-65aba1c5f294)

Sorry for the false alarm!

**Comment by nightcycle** [comment]
Closing issue
