### ISSUE TITLE
Is there a setting to delete multiple empty lines?

### ISSUE THREAD

**Issue by Gellipapa** [JohnnyMorganz/StyLua#726]
Hi! This script is very good, but I couldn't find a way to delete multiple blank lines when formatting.

I've looked at an older scripted lua-fmt called that has this formatting option.
If there is no such option in styLua I think it would be useful to support it.

Thanks in advance for your replies.

**Comment by JohnnyMorganz** [comment]
Could you give an example of what you mean?

By default we do delete multiple blank lines, and collapse it into a single blank line

**Comment by Gellipapa** [comment]
@JohnnyMorganz Hi! Ohh it works, sorry I was inattentive.
