### ISSUE TITLE
Unknown/Invalid fields in configuration file are silently ignored

### ISSUE THREAD

**Issue by Adirelle** [JohnnyMorganz/StyLua#74]
It seems the configuration file is ignored, even when using the --config-path CLI switch. The settings of the file are ignored and whenf I introduces a typo in the file, there is no error message.

Using 0.5.0 on Windows.

**Comment by JohnnyMorganz** [comment]
Hm, that's an odd one - can you confirm what commands you tried to run, and the structure of your directory? (i.e. where is the `stylua.toml` in relation to the current working directory)

**Comment by Adirelle** [comment]
The configuration file is in the working directory. The source files are in a src/ subdirectory.

**Comment by JohnnyMorganz** [comment]
I cannot reproduce this issue.
Could you show me exactly what commands you are trying to run, and the contents of the `stylua.toml` file?

**Comment by Adirelle** [comment]
The directory:
```
$ ls -la
total 52
drwxr-xr-x 1 guillaume guillaume   512 mars  11 08:39 .
drwxr-xr-x 1 guillaume guillaume   512 mars  12 23:26 ..
-rw-r--r-- 1 guillaume guillaume   148 janv. 23 05:49 .docmeta
drwxr-xr-x 1 guillaume guillaume   512 janv. 23 05:49 docs
-rwxr-xr-x 1 guillaume guillaume   214 mars   8 18:41 .editorconfig
drwxr-xr-x 1 guillaume guillaume   512 mars  13 23:36 .git
-rw-r--r-- 1 guillaume guillaume   154 janv. 23 05:49 .gitattributes
drwxr-xr-x 1 guillaume guillaume   512 janv. 23 11:34 .github
-rw-r--r-- 1 guillaume guillaume    16 mars   8 19:16 .gitignore
-rw-r--r-- 1 guillaume guillaume    44 janv. 23 12:13 .gitmodules
-rw-r--r-- 1 guillaume guillaume 34902 janv. 23 05:49 LICENSE.md
-rwxr-xr-x 1 guillaume guillaume   181 mars   8 18:41 .luacheckrc
drwxr-xr-x 1 guillaume guillaume   512 mars   8 19:16 media
drwxr-xr-x 1 guillaume guillaume   512 janv. 23 11:29 oUF
-rw-r--r-- 1 guillaume guillaume  2295 mars  10 16:43 oUF_Adirelle.toc
-rw-r--r-- 1 guillaume guillaume  2038 mars   9 21:00 .pkgmeta
-rw-r--r-- 1 guillaume guillaume  4103 janv. 23 05:49 README.md
drwxr-xr-x 1 guillaume guillaume   512 mars  12 08:11 src
-rwxr--r-- 1 guillaume guillaume   112 mars  11 08:40 stylua.toml
drwxr-xr-x 1 guillaume guillaume   512 mars   5 19:40 tocs
```

The configuration file:
```
$ cat stylua.toml 
column_width = 120
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferSingle"
```

Command:
```
$ stylua -V
stylua 0.5.0
$ stylua src/
```

**Comment by Adirelle** [comment]
Should I test the latest version built from source ?

**Comment by JohnnyMorganz** [comment]
Ah, is your issue the `quote_style` configuration? It's mentioned on the README, but it isn't actually released yet (waiting on a few other things before I get a release).

If you do want it now, master should be stable, so you can build from source. Just clone the repo and run `cargo build --release` (assuming you have Rust/Cargo installed)

I should probably look into a way to see if there's a way to explicitly emit an error if we see an invalid config option

**Comment by Adirelle** [comment]
> Ah, is your issue the `quote_style` configuration? It's mentioned on the README, but it isn't actually released yet (waiting on a few other things before I get a release).

Ah ok.
 
> If you do want it now, master should be stable, so you can build from source. Just clone the repo and run `cargo build --release` (assuming you have Rust/Cargo installed)

I will give it a try. Rust is on my list of languages to try, anyway.

> I should probably look into if there's a way to explicitly emit an error if we see an invalid config option/typo

I am actually surprised this is not the default behavior.

**Comment by JohnnyMorganz** [comment]
> I am actually surprised this is not the default behavior.

I actually also assumed it was - but it seems that it is not the case. I think this is something in the toml/serde library that I need to look at
