### ISSUE TITLE
[Suggestion] Support .editorconfig

### ISSUE THREAD

**Issue by Adirelle** [JohnnyMorganz/StyLua#75]
Given that [.editorconfig file](https://editorconfig.org/) provides some settings that are supported by stylua, it could be handy to read that file to avoid duplicating these settings.

**Comment by LastTalon** [comment]
I believe the way prettier does this is to allow an option to defer to the `.editorconfig` file. Would probably be a good option here as well.

**Comment by JohnnyMorganz** [comment]
Interesting idea, which might be nice to have. 

I think I'll most likely support project-level editorconfig, rather than a global one, so that it is more noticeable what kind of settings are being used.

**Comment by Adirelle** [comment]
> 
> 
> I believe the way prettier does this is to allow an option to defer to the `.editorconfig` file. Would probably be a good option here as well.

editorconfig provides libraries for several languages, so prettier probably used the one for js.
