### ISSUE TITLE
Large arrays are always expanded, even if there's no newline between opening brace and first element

### ISSUE THREAD

**Issue by Duckwhale** [JohnnyMorganz/StyLua#766]
Hello! Going by the description provided in [this issue](https://github.com/JohnnyMorganz/StyLua/issues/264), I expected the formatting behavior for large arrays to be as follows:

> The style that StyLua preserves here is whether to leave a table expanded, this is checked by looking for a newline character between the first brace and first element in the table.

However, it seems that this only applies when the entirety of the array fits into a single line:

```lua
return {	-0.5,
	0,
	-0.5,
	0.5,
	0,
	-0.5,
	0.5,
	0,
	0.5,
	-0.5,
	0,
	0.5,
}
```

is formatted as 

```lua
return { -0.5, 0, -0.5, 0.5, 0, -0.5, 0.5, 0, 0.5, -0.5, 0, 0.5 }
```

which does match the above description. However, if the array is large, such as this

```lua
return {-0.5,0,-0.5,0.5,0,-0.5,0,1,0,0.5,0,0.5,-0.5,0,0.5,0,1,0,0.5,0,-0.5,0.5,0,0.5,0,1,0,-0.5,0,0.5,-0.5,0,-0.5,0,1,0,-0.5,0,-0.5,0.5,0,-0.5,0.5,0,0.5,-0.5,0,0.5}
```

then the result is a single array element per line, with newline and extra space:

<details>
  <summary>Large array (example) - click to expand</summary>

```lua
return {
	-0.5,
	0,
	-0.5,
	0.5,
	0,
	-0.5,
	0,
	1,
	0,
	0.5,
	0,
	0.5,
	-0.5,
	0,
	0.5,
	0,
	1,
	0,
	0.5,
	0,
	-0.5,
	0.5,
	0,
	0.5,
	0,
	1,
	0,
	-0.5,
	0,
	0.5,
	-0.5,
	0,
	-0.5,
	0,
	1,
	0,
	-0.5,
	0,
	-0.5,
	0.5,
	0,
	-0.5,
	0.5,
	0,
	0.5,
	-0.5,
	0,
	0.5,
}

```
</details>

This means that the only way to get the desired formatting is to manually format the array and add ```-- stylua: ignore```.
Is this the intended behavior? I would expect that the formatted array end up much more compact if I remove the initial newline:

One option would be to break (roughly) after the maximum line length has been reached. Another to just never break (in this case).

The reason I even care about this is because I've got some larger fixtures that represent generated geometry; both inline and if stored in a separate file, these increase in size by almost 100%, while also becoming more difficult to read and increasing the diff size when changed. Naturally, there are other ways of storing this data, but binary formats would complicate my tests and also render diffs useless.

As a workaround, I've disabled formatting via ```-- stylua: ignore```, but peppering the code with meta-comments doesn't seem ideal.

I suppose I can live with that if the result I described is indeed expected, but I still wanted to report it just in case it isn't.

**Comment by JohnnyMorganz** [comment]
Yes, this is expected. The newline trick is only to force expansion, as commonly there are cases where you don't want a table collapsed into a less readable single line. The goal of the tool is to keep code within the column width as much of possible. Expanding a small table stays within this goal, but collapsing a large table breaks this rule. If we didn't expand large tables at all, we wouldn't really be applying formatting.

The only solution is indeed to use ignore comments here. Generated/binary content in larger tables are typically less common, which is why we stick with this.

**Comment by Duckwhale** [comment]
Fair enough. Thanks for the quick reply!
