### ISSUE TITLE
Allow configuring stylua.toml location in extension

### ISSUE THREAD

**Issue by NFLD99** [JohnnyMorganz/StyLua#782]
i have some arrays and if they exceed 113 chars long, it makes them a newline, mess and makes the array no longer look neat 
note: i use the VSCode extension, i tried making the toml file in `AppData\Roaming\Code\User\globalStorage\johnnymorganz.stylua` with no luck

**Comment by JohnnyMorganz** [comment]
The `stylua.toml` file should be located inside the workspace/folder you have open

**Comment by NFLD99** [comment]
Where do I put it for non folder open instances?

**Comment by JohnnyMorganz** [comment]
Hm, I don't think that has really been considered. We could add a config option for this

**Comment by jdahlblom** [comment]
Hi!

I have ```.stylua.toml``` in the root of the project. Working with VS Code.
```
column_width = 300

[sort_requires]
enabled = true
```
But it keeps on breaking on breaking this (102 chars):
```FC3:defineString("FC3_ALTITUDE", function()	return altitude or "000000"end, 6, "Altitude", "Altitude")```

Project settings.json is :
```
{
    "editor.formatOnSave": true,
    "[lua]": {
        "editor.defaultFormatter": "JohnnyMorganz.stylua"
    },
    "stylua.targetReleaseVersion": "v0.17.0",
    "Lua.runtime.version": "Lua 5.1",
    "Lua.workspace.library": [
        "DCS_API_defs.lua",
        "${3rd}/lfs/library"
    ],
    "Lua.diagnostics.globals": [
        "lfs"
    ]
}
```

What am I doing wrong? Thanks!

**Comment by JohnnyMorganz** [comment]
I assume you want the function to remain on one line? By default, that does not happen. You should enable the `collapse_simple_statement` setting.
This is unrelated to the original issue though

**Comment by jdahlblom** [comment]
> I assume you want the function to remain on one line? By default, that does not happen. You should enable the `collapse_simple_statement` setting. This is unrelated to the original issue though
Thank you very much for the answer. 🥇
