### ISSUE TITLE
Upload extension to open-vsx

### ISSUE THREAD

**Issue by checkraisefold** [JohnnyMorganz/StyLua#783]
this would be useful for users of VSCodium and such so they don't have to manually download and update the vsix off the vscode marketplace
https://open-vsx.org/

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/StyLua/commit/af93051e6fff29c63fd89eb4b4105742f9bd3026 adds a workflow to manage vscode and openvsx publishing. The next extension release will be published to openvsx

**Comment by checkraisefold** [comment]
Yippiee!!
