### ISSUE TITLE
stylua fails to format 1 line range

### ISSUE THREAD

**Issue by weixuanhu** [JohnnyMorganz/StyLua#804]
stylua version : 0.18.2

test file as below.
```
A=function()
a= 5
end
```

My purpose is to only format second line `a= 5`. Notice the range of second line is 13 to 16.
command : `stylua test.lua --range-start 13 --range-end 16` fails to format the second line.

**Comment by JohnnyMorganz** [comment]
I think the range of the second line ends at `17`, not `16`, which is why this was not working.
If I swap 16 -> 17 it works

**Comment by JohnnyMorganz** [comment]
Going to close this as resolved. If you have anything further, feel free to reopen.
