### ISSUE TITLE
Add a function to set config on wasm version 

### ISSUE THREAD

**Issue by Barocena** [JohnnyMorganz/StyLua#805]
Currently the only way to add settings to stylua is with creating Config object and method chaining like this
`Stylua.Config.new().with_Config_name(Stylua.ConfigName.Option).with_Config_name(...`
while this is ok for predefined configs, ~~it is not possible to add configs dynamically from a dictionary~~.
something like this
```js
var Config = Stylua.Config.new()

Config.set("ConfigName","Option") // option can either be string or enum
// or
Config.Set({
  "ConfigName": "Option",
  "ConfigName2": "Option"
})
```
would be great

**Comment by JohnnyMorganz** [comment]
I've changed the access pattern so it is more ergonomic
