### ISSUE TITLE
`GLIBC_2.28` not found on Ubuntu 18.04

### ISSUE THREAD

**Issue by zydou** [JohnnyMorganz/StyLua#806]
```sh
#!/usr/bin/env bash

curl -LO https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.2/stylua-linux-x86_64.zip
unzip stylua-linux-x86_64.zip
./stylua --version
```

Output:
```
./stylua: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./stylua)
```

System info:
```sh
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

```sh
$ strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.5) stable release version 2.27.
```

BTW, the `stylua` built on the host machine via `cargo build` works fine.

**Comment by zydou** [comment]
I managed to build it on Ubuntu Trusty (Ubuntu 14.04).

Here is the `Dockerfile`
https://github.com/zydou/stylua/blob/main/Dockerfile

**Comment by JohnnyMorganz** [comment]
Hey,
Yes, the Linux release is built on GitHub Action runners which run on 22.04 I believe. This causes it to use a higher version of GLIBC than that which is available on 18.04 now.

Since GitHub Actions removed support for 18.04, we no longer build for it, and therefore unfortunately we do not support it in our release. Like you said, building from source locally works completely fine.

**Comment by zydou** [comment]
How about adjusting the CI to build with Docker?

ref: https://github.com/zydou/stylua/blob/main/.github/workflows/build.yml

**Comment by JohnnyMorganz** [comment]
Thanks for the docker setup insight, but unfortunately I am not currently interested in maintaining building it via Docker, as it may cause pain in the future.
I wish GitHub did not aggressively remove old ubuntu releases.
