### ISSUE TITLE
Modification time of unchanged files are changed

### ISSUE THREAD

**Issue by dundargoc** [JohnnyMorganz/StyLua#827]
Hello. I noticed that the modification time of files that are "unchanged" are still changed. This causes our buildsystem to always run stylua even when it's not needed, since it uses modification time to determine whether a file has been changed or not. I would like to make the feature request to only change modification time if the file is actually changed and not otherwise. Thank you for your time!

Inpsired by this PR: https://github.com/neovim/neovim/pull/26393

**Comment by alerque** [comment]
I agree this is a bug and should be fixed.

In the mean time you might be interested in a utility I wrote [`git-warp-time`](https://github.com/alerque/git-warp-time) that can be used in build systems or Git hooks or CI or anywhere else to keep timestamp based build systems from rebuilding things that haven't actually been modified.
