### ISSUE TITLE
Ignore VCS ignored files

### ISSUE THREAD

**Issue by alerque** [JohnnyMorganz/StyLua#833]
I found that Stylua honors a `.styluaignore` file, but it would be much more useful to my projects if it would just ignore everything in `.gitignore`. Ruff and some other formatters do this and it makes it easy to avoid modifying vendored or generated code.

**Comment by JohnnyMorganz** [comment]
I don't remember why we didn't decide to ignore these files in the first place, but sounds reasonable to me.
For some reason we disabled ignoring at https://github.com/JohnnyMorganz/StyLua/blob/5de9a1da8a8dc628b98240e12ffe24c7fdbbea6e/src/cli/main.rs#L316
