### ISSUE TITLE
Stylua extension won't format files

### ISSUE THREAD

**Issue by RatIsMyUsername** [JohnnyMorganz/StyLua#846]
I suddenty noticed that my lua files don't get formatted automatically on save anymore. I have been using the following .vscode settings.json file to configure the styling options and it had been working fine until now:
![image](https://github.com/JohnnyMorganz/StyLua/assets/46536483/a5d8ca03-d848-4b0e-a617-1bebdcabec76)

Running Stylua from terminal formats the code. However the extension seems to have a problem because CTRL + SHIFT + P -> Format Document does not do anything while I have stylua set as a default formatter in VSCode settings too
![image](https://github.com/JohnnyMorganz/StyLua/assets/46536483/f70d0634-c722-4494-b4de-3f2cd16f07a7)

I have tried reinstalling vscode, stylua extension and stylua CLI many times but to no avail

**Comment by NotNite** [comment]
Also experiencing this - interestingly enough my VSCode says it's on 1.6.0 but the website says 1.6.2 is latest. No updates available in the editor itself, though.

**Comment by JohnnyMorganz** [comment]
Do you have stylua installed via aftman as well? There is currently an aftman bug that is causing issues. If so, please disable the setting `stylua.searchBinaryInPATH`, or temporarily downgrade to 1.5 until it is resolved. Sorry about that

**Comment by RatIsMyUsername** [comment]
Yeah I am using Aftman. Disabling the `stylua.searchBinaryInPATH` fixed it, thank you

**Comment by JohnnyMorganz** [comment]
I released a new extension version that disables this setting by default until Aftman is fixed

Relevant aftman bug: https://github.com/LPGhatguy/aftman/issues/54
