### ISSUE TITLE
1.6.0 doesn't seem to be supporting my Lua files

### ISSUE THREAD

**Issue by LordOfSpelunky** [JohnnyMorganz/StyLua#849]
StyLua on 1.6.0 no longer seems to be recognized as a formatter for Lua. 

I have provided a custom path. Disabling this and/or disabling the looking in PATH parameter don't seem to work. Downgrading to 1.5.0 does work.

I don't use Luau LSP, so my language code is `lua`.

**Comment by JohnnyMorganz** [comment]
In the output tab, is there a "StyLua" output group? If so, can you show what's there.

If not, can you see if there's anything related to StyLua in the "extension host" output, or the Developer Console

**Comment by JohnnyMorganz** [comment]
Ah, 1.6.0 has a bug. In the extension host output you will most likely find the error "cannot find module 'which'".

Please can you upgrade your extension version? The latest is currently 1.6.3

**Comment by LordOfSpelunky** [comment]
![image](https://github.com/JohnnyMorganz/StyLua/assets/147883041/7fb234d1-a8d9-436b-adc3-cc9eab4cf726)

Are you sure? I don't see it

**Comment by JohnnyMorganz** [comment]
Someone else mentioned the same issue. Are you on an old VSCode version?

**Comment by LordOfSpelunky** [comment]
1.75.1

**Comment by JohnnyMorganz** [comment]
> 1.75.1

Yup, that's your issue. The minimum VSCode version got bumped to 1.85, which is why you don't see the new extension versions. It's my fault for bumping the minimum version in a patch release, don't remember why exactly it needed to happen

**Comment by LordOfSpelunky** [comment]
Weird, I wonder why VSC isn't updating itself 😅  Thanks!

**Comment by LordOfSpelunky** [comment]
Ahhhh, it wasn't updating because of some silly Mac security stuff. A reinstall fixed it...thank you for helping me figure out I was wicked out of date :tada:
