### ISSUE TITLE
Could not format file: INTERNAL WARNING: Output AST may be different to input AST.

### ISSUE THREAD

**Issue by barrientosvctor** [JohnnyMorganz/StyLua#858]
I was trying to format my Lua code but I don't know why this error appears. I've examinated the formatting diff and this is the output.

![image](https://github.com/JohnnyMorganz/StyLua/assets/113469901/0c24ff7a-07d3-4a1a-bc6a-b9f8edf64867)

What could be happening here?

**Comment by JohnnyMorganz** [comment]
This is with the `--verify` flag, unfortunately false positives can happen there. The main intention of the flag is for initial migrations to highlight "potential" problems when running over lots of files, let the user manually diff, and if it is all good then it should be fine to format.

**Comment by barrientosvctor** [comment]
Is there any way to solve this problem?

I tried rewriting the code but it didn't work.

**Comment by JohnnyMorganz** [comment]
You don't really need to use --verify in your day to day, it is for initial formatting of a lot of files. Stylua is pretty stable enough now to not produce invalid code, and even then it is easier to pick up and issues during day-to-day formatting

**Comment by barrientosvctor** [comment]
So, how can I format my Lua code according to my stylua.toml file using the Stylua's npm package?

Does Stylua has some command that formats my code automatically, or do I need to format my code by myself?
