### ISSUE TITLE
Unable to format lua 5.4 code

### ISSUE THREAD

**Issue by mikavilpas** [JohnnyMorganz/StyLua#860]
Hi! I'm working on a project and trying to add support for checking lua formatting using stylua here https://github.com/sxyazi/yazi/pull/1029

Here are some findings:

- using stylua 0.20.0
- I am on osx (arm architecture) and installed stylua using `cargo install stylua --features lua54`. The files in the project can be formatted locally ($ which stylua reports the binary to be in `/Users/mikavilpas/.cargo/bin/stylua`)
- if I download version 0.20.0 [here](https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-macos-aarch64.zip), that version reports this
  issue:

  ```sh
  $ xattr -d com.apple.quarantine ~/Downloads/stylua

  $ ~/Downloads/stylua .
  error: could not format file ./yazi-plugin/preset/plugins/mime.lua: error parsing: error occurred while creating ast: unexpected token `until`. (starting from line 57, character 2 and ending on line 57, character 7)
  additional information: expected identifier after `::`

  ❯ ~/Downloads/stylua --version
  stylua 0.20.0
  ```

- I tried a couple of other versions from the last two years, but they all had a similar issue.

This is reproducible using this repository (StyLua itself). Example:

```sh
❯ ~/Downloads/stylua --version
stylua 0.20.0

$ ~/Downloads/stylua .
error: could not format file ./tests/inputs-full_moon/goto-as-identifier.lua: error parsing: error occurred while creating ast: unexpected token `goto`. (starting from line 2, character 6 and ending on line 2, character 10)
additional information: expected name
-- Note: fragment variable definitions are experimental and may be changed
-- or removed in the future.
-- Note: fragment variable definitions are experimental and may be changed
-- or removed in the future.
-- Note: fragment variable definitions are experimental and may be changed
-- or removed in the future.
```

**Comment by JohnnyMorganz** [comment]
Sounds like you are experiencing the same problem as https://github.com/JohnnyMorganz/StyLua/issues/407

Unfortunately the stylua release binaries are built with all feature flags enabled, and the Luau type assertion syntax conflicts with Lua 5.2 label syntax.

You can use cargo to build a binary with only lua54 enabled and that should hopefully work

**Comment by mikavilpas** [comment]
Thank you for the response! My issue is resolved.
