### ISSUE TITLE
[Lua 5.2] Parsing error when label is used after break

### ISSUE THREAD

**Issue by raiguard** [JohnnyMorganz/StyLua#861]
Attempting to format this valid Lua code:
```lua
for i = 1, 10 do
  if i < 8 then
    print(i)
    goto continue
  end
  break
  ::continue::
end
```

gives the following error:
```
error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `::`. (starting from line 52, character 5 and ending on line 52, character 7)
additional information: expected 'end'
```
This is likely a full-moon issue rather than something specific to stylua, but I don't want to jump the gun just in case.

**Comment by JohnnyMorganz** [comment]
This is the same issue as #402

The stylua release binaries are built with all feature flags enabled, and the Luau type assertion syntax conflicts with Lua 5.2 label syntax.

You can use cargo to build a binary with only lua52 enabled and that should work. Hopefully in the next major release we will have runtime configurable syntax selection

**Comment by JohnnyMorganz** [comment]
The next release of StyLua will give the ability to configure the syntax at runtime in your `.stylua.toml` file.

```toml
syntax = "Lua52"
```

Or alternatively specify it on the command line, `stylua --syntax lua52 file.lua`

This should resolve this issue
