### ISSUE TITLE
Add support for Lua 5.2 syntax

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#87]
This is a tracking issue in relation to support for formatting Lua 5.2 syntax.

Note: support for Lua 5.2 syntax is dependent on support being provided by [full-moon](https://github.com/Kampfkarren/full-moon), the syntax parser used.

## Syntax

- [x] Goto and label statements
- [ ] String hex escapes and `\z` (#91): Note, support for `\z` and strings taking multiple lines is currently not provided in full-moon.

If there is any other syntax currently missing from the above list, please comment and let me know

**Comment by LastTalon** [comment]
I believe 5.2 added `\z` and hex escapes as well as hex floats.
