### ISSUE TITLE
label declaration after variable assignment/declaration gives `error parsing: error occurred while creating ast: unexpected token \`end\``

### ISSUE THREAD

**Issue by thunder-coding** [JohnnyMorganz/StyLua#876]
## Lua code to reproduce the error:

```lua
while true do
  local x = 3
  ::continue::
end
```
```lua
while true do
  x = 2
  ::continue::
end
```

Can also be reproduced with if statements instead of while loops

## Output:
```bash
$ stylua x.lua
error: could not format file x.lua: error parsing: error occurred while creating ast: unexpected token `end`. (starting from line 4, character 1 and ending on line 4, character 4)
additional information: expected identifier after `::`
```

## Workaround

Adding a semicolon to explicitely terminate the variable declaration/assignment makes the error go away

## Additional details:
This bug was originally found while working on https://github.com/thunder-coding/zincoxide/commit/0a007af50c650269021668b3d066372571399dd3.

Stylua has been installed from Arch Linux's repository

**Comment by JohnnyMorganz** [comment]
See #407, should hopefully be fixed soon with runtime syntax selection

**Comment by thunder-coding** [comment]
Thanks for pointing out! Closing this issue as it's a duplicate of the issue you linked
