### ISSUE TITLE
Parsing error with leading & in a type

### ISSUE THREAD

**Issue by iamawatermelo** [JohnnyMorganz/StyLua#877]
```
local f: & number & string = "hi"
```

This is valid Luau code:

![image](https://github.com/user-attachments/assets/72a01115-da1a-4937-b977-9e240801a8cf)

StyLua cannot format it, though:

```
sarah@localhost ~/project (main) [2]> StyLua example.luau
error: could not format file example.luau: error parsing: error occurred while creating ast: unexpected token `&`. (starting from line 1, character 10 and ending on line 1, character 11)
additional information: expected type after colon
sarah@localhost ~/project (main) [2]> StyLua --version
stylua 0.20.0
sarah@localhost ~/project (main)>
```

StyLua was installed from aftman.

**Comment by JohnnyMorganz** [comment]
Requires support upstream in full-moon, our Luau parser

**Comment by JohnnyMorganz** [comment]
full-moon was updated in https://github.com/JohnnyMorganz/StyLua/pull/854, this should be available in the next release
