### ISSUE TITLE
Don't remove parenthesis in `Rest...` generics.

### ISSUE THREAD

**Issue by howmanysmall** [JohnnyMorganz/StyLua#884]
I don't really know how to explain this but I do have a reproduction.

```luau
-- Given this type:
type Function<T..., R...> = any

do
    type ThisIsOkay = Function<(), ({[string]: number})>
    type ThisIsInvalidAndWhatResultsFromFormatting = Function<(), {[string]: number}>
end

do
    type ThisIsOkay2 = Function<(string), ({[string]: number})>
    type ThisIsInvalidAndWhatResultsFromFormatting2 = Function<string, {[string]: number}>
end
```

Basically, if there's two `Rest...` generics in a type, you should not format away the parenthesis for any of them.

**Comment by JohnnyMorganz** [comment]
I cannot reproduce this. This should've been fixed in https://github.com/JohnnyMorganz/StyLua/pull/730

Are you on the latest version?

**Comment by howmanysmall** [comment]
oh good lord i was WAY out of date
