### ISSUE TITLE
[QUESTION] Neovim::conform default formatting options

### ISSUE THREAD

**Issue by Blackjacx** [JohnnyMorganz/StyLua#886]
Hey ✌️ 

nice formatter tool 👍 I just try to globally raise my line length in neovim. I use the plugin conform for formatting and I wondered if I can customize the global defaults for Stylua [this way](https://github.com/stevearc/conform.nvim#customizing-formatters) too?

Thanks for your help!

**Comment by JohnnyMorganz** [comment]
Hi, very sorry for the delay in responding.

I'm not completely sure about this. I think this is a better question for the conform tool, about whether it can allow configuring global defaults.

Alternatively, you can set a global `.stylua.toml` file and then use `--search-parent-directories` (more info: https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#finding-the-configuration)

**Comment by JohnnyMorganz** [comment]
Going to close this issue for now, let me know if you have any further questions!
