### ISSUE TITLE
Typecasting gets removed if call_parentheses is `None`

### ISSUE THREAD

**Issue by PepeElToro41** [JohnnyMorganz/StyLua#897]
When you call a function with a typecasting inside like this:

```luau
Foo({} :: SomeType)
```
The parentheses and the typecast gets removed, so the code formats like this:

```luau
Foo {}
```

**Comment by JohnnyMorganz** [comment]
We'll need to keep the parentheses in this case, because `Foo {} :: SomeType` is equivalent to `(Foo {}) :: SomeType`

**Comment by JohnnyMorganz** [comment]
I actually just tested this, and I cannot reproduce. Are you running on the latest version?

**Comment by PepeElToro41** [comment]
seems fine now :D.

I was in the latest one of the VSCode extension, Im pretty sure, but it autoupdated, so I couldnt check.
