### ISSUE TITLE
after new release stdin does not repsect .stylua.toml by default

### ISSUE THREAD

**Issue by glepnir** [JohnnyMorganz/StyLua#928]
unless must set config-path .. before no need

![image](https://github.com/user-attachments/assets/22c7f2c4-60d4-478c-bc21-cd0593252d23)

**Comment by JohnnyMorganz** [comment]
Looks like a mistake in https://github.com/JohnnyMorganz/StyLua/blob/1daf4c18fb6baf687cc41082f1cc6905ced226a4/src/cli/config.rs#L96, we forget to check the current directory if stdin file path was not provided. Thanks for reporting!

As a work around, you can use `--stdin-filepath` to specify the file path for the file you're formatting. It can even be a dummy file: `--stdin-filepath ./dummy` should in theory lookup config in the current working directory

**Comment by glepnir** [comment]
sure but hope can fix in next release
