### ISSUE TITLE
Comment copied before shebang

### ISSUE THREAD

**Issue by sadSader** [JohnnyMorganz/StyLua#937]
I use stylua 0.20.0 from NeoVim.

```
#!/usr/bin/lua

local function test(x)
	return
		--comment
		x == 1 or
                x == 2
end
```

After save comment copied before shebang.
```
--comment
#!/usr/bin/lua

local function test(x)
	return
		--comment
		x == 1 or
                x == 2
end
```

**Comment by JohnnyMorganz** [comment]
This looks very similar to https://github.com/JohnnyMorganz/StyLua/issues/879

Can you try updating your stylua version?

**Comment by sadSader** [comment]
Checked stylua 2.0.2, issue is solved
