### ISSUE TITLE
Is it possible to ignore specific syntax errors?

### ISSUE THREAD

**Issue by yiruzu** [JohnnyMorganz/StyLua#939]
I’m trying to use the `?` optional chaining operator, but since it’s not supported by default, StyLua treats it as a syntax error: `unexpected token `?``

I’ve tried using `-- stylua: ignore`, but it seems this only bypasses formatting and not syntax validation.
Is there a way to make StyLua ignore specific syntax errors like this?

**Comment by JohnnyMorganz** [comment]
Unfortunately this is not possible right now. We need to have a successfully parsing syntax tree to perform formatting. Right now this is mainly for safety to verify we don't mess anything up. The `--stylua: ignore` comment is found based off the syntax tree.

Is this syntax from a particular project? e.g., I have in my backlog to see what it takes to support GMod Lua (#930) and FiveM Lua (#855)

**Comment by yiruzu** [comment]
Yes, this is for FiveM Lua. Just to make sure I understood correctly, supporting it is already on your to-do list, right?

**Comment by JohnnyMorganz** [comment]
Correct, can't promise when, but i do want to try it out sometime

**Comment by JohnnyMorganz** [comment]
Will close this issue, #855 tracks FiveM syntax support
